-- AlterTable
ALTER TABLE "erp_staff" ADD COLUMN IF NOT EXISTS "employment_type" TEXT NOT NULL DEFAULT 'Permanent';
ALTER TABLE "erp_staff" ADD COLUMN IF NOT EXISTS "basic_salary" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "erp_staff" ADD COLUMN IF NOT EXISTS "medical_allowance" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "erp_staff" ADD COLUMN IF NOT EXISTS "medical_enabled" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "erp_staff" ADD COLUMN IF NOT EXISTS "custom_allowances" JSONB NOT NULL DEFAULT '[]';
ALTER TABLE "erp_staff" ADD COLUMN IF NOT EXISTS "custom_deductions" JSONB NOT NULL DEFAULT '[]';
