-- AlterTable
ALTER TABLE "erp_staff" ADD COLUMN IF NOT EXISTS "eobi_amount" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "erp_staff" ADD COLUMN IF NOT EXISTS "eobi_enabled" BOOLEAN NOT NULL DEFAULT false;
