import type { PurchaseOrder } from "@/lib/purchase"

function formatDate(iso: string) {
  return new Date(iso).toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })
}

function buildHTML(po: PurchaseOrder, includeSupplier: boolean): string {
  const items = po.type === "imported" ? po.importedItems : po.items
  const hasPrice = po.type === "imported"

  const rows = items.map((item: any, i: number) => `
    <tr>
      <td>${i + 1}</td>
      <td>${item.description || "—"}</td>
      <td>${item.qty}</td>
      <td>${item.unit || "—"}</td>
      ${hasPrice ? `<td>$${Number(item.unitPrice || 0).toFixed(2)}</td><td>$${(item.qty * (item.unitPrice || 0)).toFixed(2)}</td>` : ""}
    </tr>
  `).join("")

  const total = hasPrice
    ? items.reduce((s: number, it: any) => s + it.qty * (it.unitPrice || 0), 0)
    : null

  const supplierBlock = includeSupplier && po.supplierNames.length > 0
    ? `<div class="section">
        <div class="label">Supplier(s)</div>
        <div class="value">${po.supplierNames.join(", ")}</div>
       </div>`
    : ""

  return `<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8"/>
<title>PO ${po.poNumber}</title>
<style>
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { font-family: Arial, sans-serif; font-size: 12px; color: #111; padding: 40px; }
  .header { display: flex; justify-content: space-between; align-items: flex-start; margin-bottom: 32px; }
  .company { font-size: 20px; font-weight: 700; color: #1a9f9a; }
  .po-title { font-size: 14px; font-weight: 600; color: #555; margin-top: 4px; }
  .po-number { font-size: 22px; font-weight: 700; text-align: right; }
  .po-date { font-size: 11px; color: #777; text-align: right; margin-top: 4px; }
  .meta { display: flex; gap: 40px; margin-bottom: 24px; }
  .section { margin-bottom: 8px; }
  .label { font-size: 10px; text-transform: uppercase; color: #999; letter-spacing: 0.05em; }
  .value { font-size: 12px; font-weight: 500; margin-top: 2px; }
  .badge { display: inline-block; padding: 2px 8px; border-radius: 4px; font-size: 10px; font-weight: 600;
           background: #e6f7f6; color: #1a9f9a; text-transform: uppercase; }
  table { width: 100%; border-collapse: collapse; margin-top: 16px; }
  thead tr { background: #f5f5f5; }
  th { padding: 8px 10px; text-align: left; font-size: 10px; text-transform: uppercase; color: #777; letter-spacing: 0.05em; border-bottom: 1px solid #e0e0e0; }
  td { padding: 8px 10px; border-bottom: 1px solid #f0f0f0; font-size: 12px; }
  .total-row td { font-weight: 700; border-top: 2px solid #e0e0e0; border-bottom: none; }
  .footer { margin-top: 40px; font-size: 10px; color: #aaa; text-align: center; }
  .notes { margin-top: 24px; padding: 12px; background: #fafafa; border-radius: 6px; border: 1px solid #eee; }
  .notes .label { margin-bottom: 4px; }
  @media print { body { padding: 20px; } }
</style>
</head>
<body>
<div class="header">
  <div>
    <div class="company">Voltrix</div>
    <div class="po-title">Purchase Order</div>
  </div>
  <div>
    <div class="po-number">${po.poNumber}</div>
    <div class="po-date">${formatDate(po.createdAt)}</div>
  </div>
</div>

<div class="meta">
  <div class="section">
    <div class="label">Created By</div>
    <div class="value">${po.createdBy}</div>
  </div>
  <div class="section">
    <div class="label">Type</div>
    <div class="value"><span class="badge">${po.type}</span></div>
  </div>
  <div class="section">
    <div class="label">Status</div>
    <div class="value">${po.status.replace(/_/g, " ")}</div>
  </div>
  ${supplierBlock}
</div>

<table>
  <thead>
    <tr>
      <th>#</th>
      <th>Description</th>
      <th>Qty</th>
      <th>Unit</th>
      ${hasPrice ? "<th>Unit Price</th><th>Total</th>" : ""}
    </tr>
  </thead>
  <tbody>
    ${rows}
    ${total !== null ? `<tr class="total-row"><td colspan="4"></td><td>Total</td><td>$${total.toFixed(2)}</td></tr>` : ""}
  </tbody>
</table>

${po.notes ? `<div class="notes"><div class="label">Notes</div><div>${po.notes}</div></div>` : ""}

<div class="footer">Generated by Voltrix ERP · ${new Date().toLocaleString()}</div>
</body>
</html>`
}

export function downloadPO(po: PurchaseOrder, includeSupplier: boolean) {
  const html = buildHTML(po, includeSupplier)
  const win = window.open("", "_blank", "width=900,height=700")
  if (!win) return
  win.document.write(html)
  win.document.close()
  win.focus()
  setTimeout(() => { win.print() }, 400)
}
