export type Product = {
  id: string
  name: string
  category: "Residential" | "Industrial" | "EV" | "BMS"
  desc: string
  fullDesc: string
  price: string
  warranty: string
  stock: "in" | "low" | "out"
  specs: { label: string; value: string }[]
  image: string
}

export const products: Product[] = [
  {
    id: "WL-5",
    name: "WL-5",
    category: "Residential",
    desc: "5.2 KWh Battery with Built-in WiFi + Bluetooth — Wall Mount Sleek Design",
    fullDesc: "The Voltrix WL-5 is a 5.2 KWh wall-mount residential battery pack featuring built-in WiFi and Bluetooth connectivity for real-time monitoring. Its sleek design integrates seamlessly into any home environment while delivering reliable backup power.",
    price: "Rs. 210,000",
    warranty: "5 years",
    stock: "low",
    image: "/(WL-5).webp",
    specs: [
      { label: "Capacity", value: "5.2 KWh" },
      { label: "Voltage", value: "48V" },
      { label: "Connectivity", value: "WiFi + Bluetooth" },
      { label: "Mount Type", value: "Wall Mount" },
      { label: "Chemistry", value: "LiFePO₄" },
      { label: "Warranty", value: "5 years" },
    ],
  },
  {
    id: "WL-16",
    name: "WL-16",
    category: "Residential",
    desc: "Longer Backup Solution — 16 KWh wall-mount residential battery pack",
    fullDesc: "The WL-16 delivers 16 KWh of energy storage for homes requiring extended backup. Designed for longer outages, it pairs with solar systems and inverters for a complete off-grid or hybrid energy solution.",
    price: "Rs. 560,000",
    warranty: "10 years",
    stock: "in",
    image: "/(WL-5).webp",
    specs: [
      { label: "Capacity", value: "16 KWh" },
      { label: "Voltage", value: "48V" },
      { label: "Mount Type", value: "Wall Mount" },
      { label: "Chemistry", value: "LiFePO₄" },
      { label: "Cycle Life", value: "6,000+ cycles" },
      { label: "Warranty", value: "10 years" },
    ],
  },
  {
    id: "UP-12100",
    name: "UP-12100",
    category: "Residential",
    desc: "Energy Storage Battery Pack — 12 Volt UPS replacement solution",
    fullDesc: "The UP-12100 is a 12V LiFePO₄ battery pack designed as a direct replacement for lead-acid UPS batteries. It offers significantly longer life, faster charging, and lighter weight.",
    price: "Rs. 55,000",
    warranty: "5 years",
    stock: "out",
    image: "/(WL-5).webp",
    specs: [
      { label: "Voltage", value: "12V" },
      { label: "Capacity", value: "100Ah" },
      { label: "Chemistry", value: "LiFePO₄" },
      { label: "Application", value: "UPS Replacement" },
      { label: "Weight", value: "~12 kg" },
      { label: "Warranty", value: "5 years" },
    ],
  },
  {
    id: "UP-24100",
    name: "UP-24100",
    category: "Residential",
    desc: "UPS Battery Pack — 24V high-capacity residential energy storage",
    fullDesc: "The UP-24100 is a 24V 100Ah LiFePO₄ battery pack ideal for UPS systems and residential energy storage. It delivers reliable power with a long cycle life and built-in BMS protection.",
    price: "Rs. 95,000",
    warranty: "5 years",
    stock: "out",
    image: "/(WL-5).webp",
    specs: [
      { label: "Voltage", value: "24V" },
      { label: "Capacity", value: "100Ah" },
      { label: "Chemistry", value: "LiFePO₄" },
      { label: "Application", value: "UPS / Residential" },
      { label: "BMS", value: "Built-in Smart BMS" },
      { label: "Warranty", value: "5 years" },
    ],
  },
  {
    id: "A-100716",
    name: "A-100716",
    category: "BMS",
    desc: "7S–16S 100A Smart BMS with 1A balancing current — universal compatibility",
    fullDesc: "Pakistan's first indigenously developed Battery Management System. The A-100716 supports 7S to 16S LiFePO₄ configurations with 100A continuous current and 1A active balancing. Features over-charge, over-discharge, short circuit, and thermal protection.",
    price: "Rs. 14,000",
    warranty: "1 year",
    stock: "out",
    image: "/(WL-5).webp",
    specs: [
      { label: "Cell Configuration", value: "7S–16S" },
      { label: "Continuous Current", value: "100A" },
      { label: "Balancing Current", value: "1A" },
      { label: "Chemistry", value: "LiFePO₄" },
      { label: "Communication", value: "Bluetooth" },
      { label: "Warranty", value: "1 year" },
    ],
  },
  {
    id: "EV-V24",
    name: "EV Champ V-24",
    category: "EV",
    desc: "24V 27Ah LiFePO₄ — ideal drop-in replacement for graphene or lead-acid EV batteries",
    fullDesc: "The EV Champ V-24 is a 24V 27Ah LiFePO₄ battery pack engineered for electric rickshaws and light EVs. It is a direct drop-in replacement for graphene or lead-acid batteries with significantly better performance and lifespan.",
    price: "Rs. 32,000",
    warranty: "2 years",
    stock: "in",
    image: "/(WL-5).webp",
    specs: [
      { label: "Voltage", value: "24V" },
      { label: "Capacity", value: "27Ah" },
      { label: "Chemistry", value: "LiFePO₄" },
      { label: "Application", value: "Electric Rickshaw / Light EV" },
      { label: "BMS", value: "Smart BMS (Bluetooth)" },
      { label: "Warranty", value: "2 years" },
    ],
  },
  {
    id: "CS-80",
    name: "CS-80",
    category: "Industrial",
    desc: "Commercial Energy Storage — 80 KWh BESS for large-scale commercial deployments",
    fullDesc: "The CS-80 is an 80 KWh Battery Energy Storage System designed for commercial and industrial applications. It integrates with solar and grid systems to provide reliable, scalable energy storage for businesses.",
    price: "Rs. 35,00,000",
    warranty: "10 years",
    stock: "out",
    image: "/(WL-5).webp",
    specs: [
      { label: "Capacity", value: "80 KWh" },
      { label: "Application", value: "Commercial / Industrial" },
      { label: "Chemistry", value: "LiFePO₄" },
      { label: "Integration", value: "Solar + Grid" },
      { label: "Monitoring", value: "Remote SCADA" },
      { label: "Warranty", value: "10 years" },
    ],
  },
  {
    id: "BESS-232",
    name: "BESS-232 KWh",
    category: "Industrial",
    desc: "Industrial Energy Storage — 232 KWh BESS for grid-scale and industrial applications",
    fullDesc: "The BESS-232 is a 232 KWh industrial-grade Battery Energy Storage System for grid-scale deployments, factories, and large commercial facilities. Pricing is available on request based on project scope.",
    price: "Request for Quote",
    warranty: "10 years",
    stock: "in",
    image: "/(WL-5).webp",
    specs: [
      { label: "Capacity", value: "232 KWh" },
      { label: "Application", value: "Grid-scale / Industrial" },
      { label: "Chemistry", value: "LiFePO₄" },
      { label: "Scalable", value: "Yes — modular design" },
      { label: "Monitoring", value: "Remote SCADA + BMS" },
      { label: "Warranty", value: "10 years" },
    ],
  },
  {
    id: "EV-72",
    name: "EV Champ 72V",
    category: "EV",
    desc: "72V 27Ah LiFePO₄ EV Battery | 2.0 KWh | 1C/3C | Smart BMS with Bluetooth",
    fullDesc: "The EV Champ 72V delivers 2.0 KWh of energy in a compact LiFePO₄ pack. With 1C continuous and 3C peak discharge, it powers high-performance electric motorcycles and three-wheelers with a Smart BMS featuring Bluetooth diagnostics.",
    price: "Rs. 78,000",
    warranty: "2 years",
    stock: "in",
    image: "/(WL-5).webp",
    specs: [
      { label: "Voltage", value: "72V" },
      { label: "Capacity", value: "27Ah (2.0 KWh)" },
      { label: "Discharge Rate", value: "1C continuous / 3C peak" },
      { label: "Chemistry", value: "LiFePO₄" },
      { label: "BMS", value: "Smart BMS (Bluetooth)" },
      { label: "Warranty", value: "2 years" },
    ],
  },
  {
    id: "EV-60",
    name: "EV Champ 60V",
    category: "EV",
    desc: "60.8V 27Ah ≈1.65 KWh | 19S1P | 1C/3C peak | Smart BMS with Bluetooth",
    fullDesc: "The EV Champ 60V is a 19S1P LiFePO₄ pack delivering 1.65 KWh at 60.8V. Designed for electric bikes and scooters, it features a Smart BMS with Bluetooth for real-time monitoring and diagnostics.",
    price: "Rs. 67,000",
    warranty: "2 years",
    stock: "in",
    image: "/(WL-5).webp",
    specs: [
      { label: "Voltage", value: "60.8V" },
      { label: "Capacity", value: "27Ah (≈1.65 KWh)" },
      { label: "Configuration", value: "19S1P" },
      { label: "Discharge Rate", value: "1C continuous / 3C peak" },
      { label: "BMS", value: "Smart BMS (Bluetooth)" },
      { label: "Warranty", value: "2 years" },
    ],
  },
]

export const categoryColors: Record<string, string> = {
  Residential: "bg-blue-50 text-blue-600 border-blue-100",
  Industrial:  "bg-orange-50 text-orange-600 border-orange-100",
  EV:          "bg-purple-50 text-purple-600 border-purple-100",
  BMS:         "bg-neutral-100 text-neutral-600 border-neutral-200",
}
