"use client"
import { useState, useEffect } from "react"
import { getBranches, saveBranch, deleteBranch, generateBranchCode, getBranchInventory, getBranchTransferHistory, batchBranchInventoryTransfer, clearBranchTransferHistory, resetBranchInventory, type Branch, type BranchInventory, type BranchInventoryTransfer } from "@/lib/branches"
import { downloadBranchTransferHistoryPDF } from "@/lib/generate-branch-transfer-history-pdf"
import { BulkBranchTransferModal, type BulkTransferProduct } from "@/components/branches/bulk-branch-transfer-modal"
import { Package } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Badge } from "@/components/ui/badge"
import { Plus, Pencil, Trash2, X, Phone, Mail, MapPin, Building2, Loader2, User, ArrowRightLeft, FileDown, History, ArrowDownLeft, ArrowUpRight } from "lucide-react"
import { useDialog } from "@/components/ui/dialog-provider"
import { useToast } from "@/components/ui/toast"
import { useAuth } from "@/components/auth-provider"

const empty = (code: string = ""): Omit<Branch, "id" | "createdAt" | "createdBy"> => ({
  name: "", code, type: "outlet", address: "", city: "", country: "", phone: "", email: "", manager: "", status: "active", notes: "",
})

async function generateSingleBranchPdf(branch: Branch, inventoryRows: any[]) {
  const [{ default: jsPDF }, autoTableModule] = await Promise.all([
    import("jspdf"),
    import("jspdf-autotable"),
  ])
  const autoTable = (autoTableModule as any).default || autoTableModule
  const doc = new jsPDF("p", "mm", "a4")
  
  doc.setFontSize(14)
  doc.text(`Inventory Report: ${branch.name}`, 14, 16)
  
  doc.setFontSize(10)
  doc.text(`Branch Code: ${branch.code}`, 14, 22)
  doc.text(`Type: ${branch.type.replace("_", " ")}`, 14, 27)
  doc.text(`Generated: ${new Date().toLocaleString()}`, 14, 32)
  
  const body = inventoryRows.map(inv => [
    inv.productDescription || inv.itemName || inv.inventoryId || "N/A",
    String(inv.quantity),
    inv.unit || "",
    inv.assignedAt ? new Date(inv.assignedAt).toLocaleDateString() : "-"
  ])

  autoTable(doc, {
    startY: 38,
    head: [["Item Description", "Qty", "Unit", "Date"]],
    body: body,
    styles: { fontSize: 8, cellPadding: 2 },
    headStyles: { fillColor: [31, 172, 166] },
  })
  
  doc.save(`${branch.code}-inventory-${new Date().toISOString().slice(0, 10)}.pdf`)
}

// ── Branch Form ────────────────────────────────────────────────
function BranchForm({ initial, onSave, onCancel, isLoading, autoGenerated }: {
  initial: Omit<Branch, "id" | "createdAt" | "createdBy">
  onSave: (b: Omit<Branch, "id" | "createdAt" | "createdBy">) => void
  onCancel: () => void
  isLoading?: boolean
  autoGenerated?: boolean
}) {
  const [form, setForm] = useState(initial)
  const set = (k: keyof typeof form, v: string) => setForm(f => ({ ...f, [k]: v }))

  return (
    <form onSubmit={e => { e.preventDefault(); onSave(form) }}
      className="border rounded-lg p-4 space-y-3 bg-[hsl(var(--muted))]/20">
      <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
        <div className="space-y-1 sm:col-span-2">
          <label className="text-xs font-medium">Branch Name *</label>
          <input required value={form.name} onChange={e => set("name", e.target.value)}
            placeholder="e.g. Main Outlet"
            className="w-full h-8 rounded-md border bg-[hsl(var(--background))] px-3 text-sm focus:outline-none focus:ring-1 focus:ring-[hsl(var(--ring))]" />
        </div>
        <div className="space-y-1">
          <label className="text-xs font-medium">Branch Code *</label>
          <input required value={form.code} onChange={e => set("code", e.target.value)}
            placeholder="e.g. BR001"
            readOnly={autoGenerated}
            className={`w-full h-8 rounded-md border bg-[hsl(var(--background))] px-3 text-sm focus:outline-none focus:ring-1 focus:ring-[hsl(var(--ring))] ${autoGenerated ? "bg-[hsl(var(--muted))]/50 cursor-not-allowed" : ""}`}
          />
          {autoGenerated && <p className="text-[10px] text-[hsl(var(--muted-foreground))]">Auto-generated</p>}
        </div>
        <div className="space-y-1">
          <label className="text-xs font-medium">Type *</label>
          <select required value={form.type} onChange={e => set("type", e.target.value)}
            className="w-full h-8 rounded-md border bg-[hsl(var(--background))] px-3 text-sm focus:outline-none focus:ring-1 focus:ring-[hsl(var(--ring))]">
            <option value="outlet">Outlet</option>
            <option value="store">Store</option>
            <option value="warehouse">Warehouse</option>
            <option value="branch_warehouse">Branch Warehouse</option>
            <option value="main_warehouse">Main Warehouse</option>
            <option value="office">Office</option>
          </select>
        </div>
        <div className="space-y-1">
          <label className="text-xs font-medium">Manager</label>
          <input value={form.manager} onChange={e => set("manager", e.target.value)}
            placeholder="Manager name"
            className="w-full h-8 rounded-md border bg-[hsl(var(--background))] px-3 text-sm focus:outline-none focus:ring-1 focus:ring-[hsl(var(--ring))]" />
        </div>
        <div className="space-y-1">
          <label className="text-xs font-medium">Status *</label>
          <select required value={form.status} onChange={e => set("status", e.target.value)}
            className="w-full h-8 rounded-md border bg-[hsl(var(--background))] px-3 text-sm focus:outline-none focus:ring-1 focus:ring-[hsl(var(--ring))]">
            <option value="active">Active</option>
            <option value="inactive">Inactive</option>
          </select>
        </div>
        <div className="space-y-1">
          <label className="text-xs font-medium">Phone</label>
          <input value={form.phone} onChange={e => set("phone", e.target.value)}
            placeholder="+92 300 0000000"
            className="w-full h-8 rounded-md border bg-[hsl(var(--background))] px-3 text-sm focus:outline-none focus:ring-1 focus:ring-[hsl(var(--ring))]" />
        </div>
        <div className="space-y-1">
          <label className="text-xs font-medium">Email</label>
          <input type="email" value={form.email} onChange={e => set("email", e.target.value)}
            className="w-full h-8 rounded-md border bg-[hsl(var(--background))] px-3 text-sm focus:outline-none focus:ring-1 focus:ring-[hsl(var(--ring))]" />
        </div>
        <div className="space-y-1">
          <label className="text-xs font-medium">Location</label>
          <input value={form.city} onChange={e => set("city", e.target.value)}
            className="w-full h-8 rounded-md border bg-[hsl(var(--background))] px-3 text-sm focus:outline-none focus:ring-1 focus:ring-[hsl(var(--ring))]" />
        </div>
        <div className="space-y-1 sm:col-span-2">
          <label className="text-xs font-medium">Address</label>
          <input value={form.address} onChange={e => set("address", e.target.value)}
            className="w-full h-8 rounded-md border bg-[hsl(var(--background))] px-3 text-sm focus:outline-none focus:ring-1 focus:ring-[hsl(var(--ring))]" />
        </div>
        <div className="space-y-1">
          <label className="text-xs font-medium">Country</label>
          <input value={form.country} onChange={e => set("country", e.target.value)}
            className="w-full h-8 rounded-md border bg-[hsl(var(--background))] px-3 text-sm focus:outline-none focus:ring-1 focus:ring-[hsl(var(--ring))]" />
        </div>
        <div className="space-y-1 sm:col-span-2">
          <label className="text-xs font-medium">Notes</label>
          <textarea value={form.notes} onChange={e => set("notes", e.target.value)} rows={2}
            className="w-full rounded-md border bg-[hsl(var(--background))] px-3 py-2 text-sm focus:outline-none focus:ring-1 focus:ring-[hsl(var(--ring))] resize-none" />
        </div>
      </div>
      <div className="flex gap-2">
        <Button type="submit" size="sm" className="h-8 cursor-pointer" disabled={isLoading}>
          {isLoading ? (
            <>
              <Loader2 className="h-3.5 w-3.5 animate-spin mr-1" />
              Saving...
            </>
          ) : (
            "Save Branch"
          )}
        </Button>
        <Button type="button" variant="outline" size="sm" className="h-8 cursor-pointer" onClick={onCancel} disabled={isLoading}>Cancel</Button>
      </div>
    </form>
  )
}

// ── Branch Detail Popup ────────────────────────────────────────
function BranchDetail({ branch, branches, onClose, onEdit, onDelete }: {
  branch: Branch
  branches: Branch[]
  onClose: () => void
  onEdit: () => void
  onDelete: () => void
}) {
  const [inventory, setInventory] = useState<BranchInventory[]>([])
  const [loadingInventory, setLoadingInventory] = useState(true)
  const [showBulkTransfer, setShowBulkTransfer] = useState(false)
  const [bulkTransferMode, setBulkTransferMode] = useState<"dispatch" | "transfer">("dispatch")
  const [bulkPreselectId, setBulkPreselectId] = useState<string | null>(null)
  const [bulkSubmitting, setBulkSubmitting] = useState(false)
  const [transferHistory, setTransferHistory] = useState<BranchInventoryTransfer[]>([])
  const [loadingTransferHistory, setLoadingTransferHistory] = useState(true)
  const [clearingHistory, setClearingHistory] = useState(false)
  const [returningToMain, setReturningToMain] = useState(false)
  const { toast } = useToast()
  const { confirm } = useDialog()
  const { user } = useAuth()
  const isMainWarehouse = branch.type === "main_warehouse"

  useEffect(() => {
    setLoadingInventory(true)
    getBranchInventory(branch.id).then(data => {
      setInventory(data)
      setLoadingInventory(false)
    })
    loadTransferHistory()
  }, [branch.id])

  async function loadTransferHistory() {
    setLoadingTransferHistory(true)
    try {
      const history = await getBranchTransferHistory(branch.id)
      setTransferHistory(history)
    } catch {
      setTransferHistory([])
    } finally {
      setLoadingTransferHistory(false)
    }
  }

  async function reloadInventory() {
    const data = await getBranchInventory(branch.id)
    setInventory(data)
  }

  async function handleClearTransferHistory() {
    const ok = await confirm({
      type: "confirm",
      title: "Clear transfer history",
      message: `Remove all transfer history records for ${branch.name}? This cannot be undone.`,
      confirmLabel: "Clear history",
    })
    if (!ok) return
    setClearingHistory(true)
    try {
      await clearBranchTransferHistory(branch.id)
      await loadTransferHistory()
      toast({
        type: "success",
        title: "History cleared",
        message: "Transfer history has been removed for this branch.",
        duration: 3000,
      })
    } catch {
      toast({
        type: "error",
        title: "Failed",
        message: "Could not clear transfer history.",
        duration: 3000,
      })
    } finally {
      setClearingHistory(false)
    }
  }

  async function handleReturnInventoryToMain() {
    const ok = await confirm({
      type: "confirm",
      title: "Return inventory to main warehouse",
      message: `Move all transferred stock from ${branch.name} back to the main warehouse and clear this branch's transfer history?`,
      confirmLabel: "Return to main",
    })
    if (!ok) return
    setReturningToMain(true)
    try {
      await resetBranchInventory({ branchId: branch.id, all: false })
      await reloadInventory()
      await loadTransferHistory()
      toast({
        type: "success",
        title: "Inventory returned",
        message: "Stock is back in the main warehouse and transfer history was cleared.",
        duration: 3000,
      })
    } catch {
      toast({
        type: "error",
        title: "Failed",
        message: "Could not return inventory to the main warehouse.",
        duration: 3000,
      })
    } finally {
      setReturningToMain(false)
    }
  }

  const bulkTransferProducts: BulkTransferProduct[] = isMainWarehouse
    ? inventory.map((item) => {
        const canSend = (item.inStock ?? item.quantity) > 0
        const stockId =
          item.inventoryId && !item.inventoryId.startsWith("wh:")
            ? item.inventoryId
            : undefined
        return {
          id: item.id,
          label: item.itemName || item.productDescription || item.model || "Item",
          sublabel: item.model || item.productDescription,
          model: item.model,
          productName: item.itemName,
          maxQty: item.inStock ?? item.quantity,
          unit: item.unit || "pcs",
          inventoryId: stockId,
          selectable: canSend,
          unselectableReason: canSend ? undefined : "No units in stock",
        }
      })
    : inventory
        .filter((item) => item.quantity > 0)
        .map((item) => ({
          id: item.id,
          label: item.productDescription || item.inventoryId,
          sublabel: `${item.quantity} ${item.unit} available`,
          maxQty: item.quantity,
          unit: item.unit || "pcs",
          fromBranchInventoryId: item.id,
          selectable: true,
        }))

  function openBulkTransfer(mode: "dispatch" | "transfer", preselectId?: string) {
    setBulkTransferMode(mode)
    setBulkPreselectId(preselectId ?? null)
    setShowBulkTransfer(true)
  }

  async function handleBulkTransferSubmit(payload: {
    toBranchId: string
    lines: Array<{
      inventoryId?: string
      fromBranchInventoryId?: string
      quantity: number
      unit?: string
      userNote?: string
    }>
  }) {
    const destination = branches.find((b) => b.id === payload.toBranchId)
    setBulkSubmitting(true)
    try {
      const result = await batchBranchInventoryTransfer({
        mode: bulkTransferMode,
        toBranchId: payload.toBranchId,
        fromBranchId: isMainWarehouse ? branch.id : undefined,
        fromBranchName: branch.name,
        fromBranchCode: branch.code,
        destinationBranchCode: destination?.code,
        assignedBy: user?.name || "system",
        systemNotes: isMainWarehouse ? `Dispatched from main warehouse ${branch.code}` : undefined,
        lines: payload.lines,
      })
      await reloadInventory()
      await loadTransferHistory()
      setShowBulkTransfer(false)
      setBulkPreselectId(null)
      if (result.failed > 0) {
        toast({
          type: "error",
          title: "Partial transfer",
          message: `${result.succeeded} saved, ${result.failed} failed. Check transfer history.`,
          duration: 5000,
        })
      } else {
        toast({
          type: "success",
          title: bulkTransferMode === "dispatch" ? "Inventory sent" : "Transfer complete",
          message: `${result.succeeded} transfer${result.succeeded === 1 ? "" : "s"} saved to history.`,
          duration: 4000,
        })
      }
    } catch {
      toast({
        type: "error",
        title: "Transfer failed",
        message: "Could not save transfers. Please try again.",
        duration: 4000,
      })
    } finally {
      setBulkSubmitting(false)
    }
  }

  const inventoryRows = inventory

  const mainWarehouseSummary = isMainWarehouse
    ? {
        models: inventory.length,
        boxes: inventory.reduce((sum, row) => sum + (row.totalUnits ?? row.quantity ?? 0), 0),
        inStock: inventory.reduce((sum, row) => sum + (row.inStock ?? row.quantity ?? 0), 0),
      }
    : null

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 backdrop-blur-sm p-4" onClick={onClose}>
      <div className="w-full max-w-3xl rounded-2xl border bg-[hsl(var(--card))] shadow-2xl overflow-hidden max-h-[90vh] flex flex-col" onClick={e => e.stopPropagation()}>
        {/* Header */}
        <div className="px-6 pt-6 pb-4">
          <div className="flex items-start justify-between">
            <div className="flex items-center gap-4">
              <div className="flex h-16 w-16 items-center justify-center rounded-full bg-[#1faca6] text-2xl font-bold text-white shadow-sm">
                {branch.name.charAt(0).toUpperCase()}
              </div>
              <div>
                <p className="text-lg font-semibold">{branch.name}</p>
                <p className="text-sm text-[hsl(var(--muted-foreground))] mt-0.5">{branch.code}</p>
                <div className="mt-2">
                  <Badge variant={branch.status === "active" ? "success" : "secondary"} className="text-[10px] px-2 py-0.5">
                    {branch.status}
                  </Badge>
                  <Badge variant="info" className="text-[10px] px-2 py-0.5 ml-1">
                    {branch.type}
                  </Badge>
                </div>
              </div>
            </div>
            <Button variant="ghost" size="icon" className="h-8 w-8 -mt-1 -mr-2 cursor-pointer" onClick={onClose}>
              <X className="h-4 w-4" />
            </Button>
          </div>
        </div>

        {/* Details */}
        <div className="px-6 pb-4 space-y-3 overflow-y-auto">
          {branch.manager && (
            <div className="flex items-center gap-3 p-2.5 rounded-lg bg-[hsl(var(--muted))]/30">
              <div className="flex h-8 w-8 shrink-0 items-center justify-center rounded-lg bg-[hsl(var(--background))]">
                <User className="h-4 w-4 text-[hsl(var(--muted-foreground))]" />
              </div>
              <div className="min-w-0">
                <p className="text-[10px] text-[hsl(var(--muted-foreground))] uppercase tracking-wider font-medium">Manager</p>
                <p className="text-sm font-medium truncate">{branch.manager}</p>
              </div>
            </div>
          )}
          {branch.phone && (
            <div className="flex items-center gap-3 p-2.5 rounded-lg bg-[hsl(var(--muted))]/30">
              <div className="flex h-8 w-8 shrink-0 items-center justify-center rounded-lg bg-[hsl(var(--background))]">
                <Phone className="h-4 w-4 text-[hsl(var(--muted-foreground))]" />
              </div>
              <div className="min-w-0">
                <p className="text-[10px] text-[hsl(var(--muted-foreground))] uppercase tracking-wider font-medium">Phone</p>
                <p className="text-sm font-medium truncate">{branch.phone}</p>
              </div>
            </div>
          )}
          {branch.email && (
            <div className="flex items-center gap-3 p-2.5 rounded-lg bg-[hsl(var(--muted))]/30">
              <div className="flex h-8 w-8 shrink-0 items-center justify-center rounded-lg bg-[hsl(var(--background))]">
                <Mail className="h-4 w-4 text-[hsl(var(--muted-foreground))]" />
              </div>
              <div className="min-w-0">
                <p className="text-[10px] text-[hsl(var(--muted-foreground))] uppercase tracking-wider font-medium">Email</p>
                <p className="text-sm font-medium truncate">{branch.email}</p>
              </div>
            </div>
          )}
          {(branch.address || branch.city) && (
            <div className="flex items-start gap-3 p-2.5 rounded-lg bg-[hsl(var(--muted))]/30">
              <div className="flex h-8 w-8 shrink-0 items-center justify-center rounded-lg bg-[hsl(var(--background))]">
                <MapPin className="h-4 w-4 text-[hsl(var(--muted-foreground))]" />
              </div>
              <div className="min-w-0">
                <p className="text-[10px] text-[hsl(var(--muted-foreground))] uppercase tracking-wider font-medium">Address</p>
                <p className="text-sm font-medium leading-snug">{branch.address}{branch.city && `, ${branch.city}`}{branch.country && `, ${branch.country}`}</p>
              </div>
            </div>
          )}
          {branch.notes && (
            <div className="border-t pt-2.5 mt-1">
              <div className="flex items-start gap-3 p-2.5 rounded-lg bg-[hsl(var(--muted))]/30">
                <div className="min-w-0">
                  <p className="text-[10px] text-[hsl(var(--muted-foreground))] uppercase tracking-wider font-medium">Notes</p>
                  <p className="text-sm font-medium">{branch.notes}</p>
                </div>
              </div>
            </div>
          )}

          {/* Inventory Section */}
          <div className="border-t pt-3 mt-1">
            <div className="flex items-center justify-between mb-2">
              <p className="text-[10px] text-[hsl(var(--muted-foreground))] uppercase tracking-wider font-medium">
                {isMainWarehouse ? "Main Warehouse Inventory" : "Transferred Inventory"}
              </p>
              <div className="flex items-center gap-1.5">
                {isMainWarehouse ? (
                  <Button
                    size="sm"
                    variant="outline"
                    className="h-6 text-[10px] cursor-pointer"
                    onClick={() => openBulkTransfer("dispatch")}
                  >
                    <ArrowRightLeft className="h-3 w-3" /> Send multiple
                  </Button>
                ) : inventory.length > 0 ? (
                  <>
                  <Button
                    size="sm"
                    variant="outline"
                    className="h-6 text-[10px] cursor-pointer text-[#1faca6] border-[#1faca6] hover:bg-[#1faca6]/10"
                    onClick={() => openBulkTransfer("transfer")}
                  >
                    <ArrowRightLeft className="h-3 w-3" /> Transfer
                  </Button>
                  <Button
                    size="sm"
                    variant="outline"
                    className="h-6 text-[10px] cursor-pointer text-orange-600 border-orange-300 hover:bg-orange-50"
                    disabled={returningToMain}
                    onClick={handleReturnInventoryToMain}
                  >
                    {returningToMain ? <Loader2 className="h-3 w-3 animate-spin" /> : <ArrowRightLeft className="h-3 w-3" />}
                    Return to main
                  </Button>
                  </>
                ) : null}
              </div>
            </div>
            {mainWarehouseSummary && mainWarehouseSummary.models > 0 && (
              <p className="text-xs text-[hsl(var(--muted-foreground))] mb-2">
                <strong className="text-[hsl(var(--foreground))]">{mainWarehouseSummary.boxes}</strong> boxes
                {" · "}
                <strong className="text-[hsl(var(--foreground))]">{mainWarehouseSummary.models}</strong> models
                {" · "}
                <strong className="text-[hsl(var(--foreground))]">{mainWarehouseSummary.inStock}</strong> in stock
              </p>
            )}
            {loadingInventory ? (
              <div className="flex items-center justify-center py-4">
                <Loader2 className="h-4 w-4 animate-spin text-[hsl(var(--muted-foreground))]" />
              </div>
            ) : inventoryRows.length === 0 ? (
              <p className="text-xs text-[hsl(var(--muted-foreground))] py-2">
                {isMainWarehouse ? "No scanned inventory yet. Use Inventory → Scan QR." : "No transferred inventory yet."}
              </p>
            ) : (
              <div className="grid grid-cols-1 md:grid-cols-2 gap-2.5 max-h-72 overflow-y-auto pr-1">
                {inventoryRows.map(inv => (
                  <div key={inv.id} className="rounded-lg border bg-[hsl(var(--background))] p-2.5">
                    <div className="flex items-start justify-between gap-2">
                      <div className="min-w-0">
                        <p className="text-xs font-semibold truncate">{inv.itemName || inv.productDescription || inv.inventoryId}</p>
                        {isMainWarehouse && inv.model && (
                          <p className="text-[10px] text-[hsl(var(--muted-foreground))] truncate">{inv.model}</p>
                        )}
                        {isMainWarehouse && inv.specs && (
                          <p className="text-[10px] text-[hsl(var(--muted-foreground))] truncate">{inv.specs}</p>
                        )}
                        {isMainWarehouse && inv.totalUnits != null && (
                          <p className="text-[10px] text-[hsl(var(--muted-foreground))] mt-1">
                            {inv.inStock ?? inv.quantity}/{inv.totalUnits} in stock
                          </p>
                        )}
                      </div>
                      <div className="flex flex-col items-end gap-1 shrink-0">
                        <Badge variant="secondary" className="text-[10px] px-2 py-0.5">
                          {inv.quantity} {inv.unit}
                        </Badge>
                        {!isMainWarehouse && (
                          <Button
                            variant="ghost"
                            size="icon"
                            className="h-6 w-6 text-[#1faca6] hover:bg-[#1faca6]/10 cursor-pointer"
                            title="Add to transfer"
                            onClick={(e) => {
                              e.stopPropagation()
                              openBulkTransfer("transfer", inv.id)
                            }}
                          >
                            <ArrowRightLeft className="h-3 w-3" />
                          </Button>
                        )}
                      </div>
                    </div>
                    {!isMainWarehouse && inv.assignedAt && (
                      <p className="text-[10px] text-[hsl(var(--muted-foreground))] mt-2">
                        Transferred: {new Date(inv.assignedAt).toLocaleDateString()}
                      </p>
                    )}
                  </div>
                ))}
              </div>
            )}
          </div>

          <div className="border-t pt-3 mt-1">
            <div className="flex items-center justify-between mb-2">
              <p className="text-[10px] text-[hsl(var(--muted-foreground))] uppercase tracking-wider font-medium flex items-center gap-1.5">
                <History className="h-3 w-3" />
                Transfer History
              </p>
              <div className="flex items-center gap-2">
                <span className="text-[10px] text-[hsl(var(--muted-foreground))]">{transferHistory.length} record{transferHistory.length === 1 ? "" : "s"}</span>
                <Button
                  size="sm"
                  variant="outline"
                  className="h-7 text-[10px] cursor-pointer text-[#1faca6] border-[#1faca6] hover:bg-[#1faca6] hover:text-white"
                  disabled={transferHistory.length === 0}
                  onClick={() => downloadBranchTransferHistoryPDF(branch, transferHistory)}
                >
                  <FileDown className="h-3 w-3 mr-1" />
                  Download PDF
                </Button>
                <Button
                  size="sm"
                  variant="outline"
                  className="h-7 text-[10px] cursor-pointer text-red-600 border-red-300 hover:bg-red-50"
                  disabled={transferHistory.length === 0 || clearingHistory}
                  onClick={handleClearTransferHistory}
                >
                  {clearingHistory ? <Loader2 className="h-3 w-3 animate-spin" /> : <Trash2 className="h-3 w-3 mr-1" />}
                  Clear history
                </Button>
              </div>
            </div>
            {loadingTransferHistory ? (
              <div className="flex items-center justify-center py-4">
                <Loader2 className="h-4 w-4 animate-spin text-[hsl(var(--muted-foreground))]" />
              </div>
            ) : transferHistory.length === 0 ? (
              <p className="text-xs text-[hsl(var(--muted-foreground))] py-2">No inventory transfers recorded for this branch yet.</p>
            ) : (
              <div className="space-y-2 max-h-56 overflow-y-auto pr-1">
                {transferHistory.map(entry => {
                  const isOutgoing = entry.fromBranchId === branch.id
                  const isIncoming = entry.toBranchId === branch.id
                  return (
                    <div key={entry.id} className="rounded-lg border bg-[hsl(var(--background))] p-2.5">
                      <div className="flex items-start justify-between gap-2">
                        <div className="min-w-0">
                          <div className="flex items-center gap-1.5">
                            {isOutgoing ? (
                              <ArrowUpRight className="h-3.5 w-3.5 text-orange-500 shrink-0" />
                            ) : isIncoming ? (
                              <ArrowDownLeft className="h-3.5 w-3.5 text-green-600 shrink-0" />
                            ) : (
                              <ArrowRightLeft className="h-3.5 w-3.5 text-[hsl(var(--muted-foreground))] shrink-0" />
                            )}
                            <p className="text-xs font-semibold truncate">{entry.productDescription}</p>
                          </div>
                          <p className="text-[10px] text-[hsl(var(--muted-foreground))] mt-1">
                            {isOutgoing ? `To ${entry.toBranchName} (${entry.toBranchCode})` : isIncoming ? `From ${entry.fromBranchName} (${entry.fromBranchCode})` : `${entry.fromBranchName} → ${entry.toBranchName}`}
                          </p>
                          <p className="text-[10px] text-[hsl(var(--muted-foreground))] mt-1 leading-relaxed">{entry.note}</p>
                        </div>
                        <div className="text-right shrink-0">
                          <Badge variant="secondary" className="text-[10px] px-2 py-0.5">
                            {entry.quantity} {entry.unit}
                          </Badge>
                          <p className="text-[10px] text-[hsl(var(--muted-foreground))] mt-1">
                            {new Date(entry.transferredAt).toLocaleString()}
                          </p>
                          <p className="text-[10px] text-[hsl(var(--muted-foreground))]">{entry.transferredBy}</p>
                        </div>
                      </div>
                    </div>
                  )
                })}
              </div>
            )}
          </div>
        </div>

        {/* Footer */}
        <div className="flex items-center gap-2 px-6 py-4 border-t bg-[hsl(var(--muted))]/20">
          <Button size="sm" variant="outline" className="h-9 text-xs cursor-pointer" onClick={onEdit}>
            <Pencil className="h-3.5 w-3.5" /> Edit
          </Button>
          <Button 
            size="sm" 
            variant="outline" 
            className="h-9 text-xs cursor-pointer text-[#1faca6] border-[#1faca6] hover:bg-[#1faca6] hover:text-white" 
            onClick={() => generateSingleBranchPdf(branch, inventoryRows)}
            disabled={inventoryRows.length === 0}
          >
            <FileDown className="h-3.5 w-3.5" /> Inventory PDF
          </Button>
          <Button
            size="sm"
            variant="outline"
            className="h-9 text-xs cursor-pointer text-[#1faca6] border-[#1faca6] hover:bg-[#1faca6] hover:text-white"
            onClick={() => downloadBranchTransferHistoryPDF(branch, transferHistory)}
            disabled={transferHistory.length === 0}
          >
            <FileDown className="h-3.5 w-3.5" /> Transfer PDF
          </Button>
          <Button size="sm" variant="ghost" className="h-9 text-xs text-red-500 hover:text-red-600 hover:bg-red-50 cursor-pointer" onClick={onDelete}>
            <Trash2 className="h-3.5 w-3.5" /> Delete
          </Button>
          <Button size="sm" variant="ghost" className="h-9 text-xs ml-auto cursor-pointer" onClick={onClose}>Close</Button>
        </div>
      </div>

      <BulkBranchTransferModal
        open={showBulkTransfer}
        onClose={() => {
          setShowBulkTransfer(false)
          setBulkPreselectId(null)
        }}
        title={
          bulkTransferMode === "dispatch"
            ? "Send multiple products to branch"
            : "Transfer multiple products"
        }
        mode={bulkTransferMode}
        products={bulkTransferProducts}
        branches={branches}
        currentBranchId={branch.id}
        preselectedProductId={bulkPreselectId}
        submitting={bulkSubmitting}
        destinationFilter={
          bulkTransferMode === "dispatch"
            ? (b) => b.type === "branch_warehouse" || b.type === "warehouse"
            : undefined
        }
        onSubmit={handleBulkTransferSubmit}
      />

    </div>

  )
}

// ── Main Tab ─────────────────────────────────────────────────────
export function BranchesTab() {
  const [branches, setBranches] = useState<Branch[]>([])
  const [loading, setLoading] = useState(true)
  const [adding, setAdding] = useState(false)
  const [editId, setEditId] = useState<string | null>(null)
  const [viewBranch, setViewBranch] = useState<Branch | null>(null)
  const [saving, setSaving] = useState(false)
  const [autoCode, setAutoCode] = useState("")
  const [exportPreviewOpen, setExportPreviewOpen] = useState(false)
  const [exportLoading, setExportLoading] = useState(false)
  const [resettingAll, setResettingAll] = useState(false)
  const [exportRows, setExportRows] = useState<Array<{
    branchName: string
    branchCode: string
    branchType: string
    item: string
    qty: number
    unit: string
    transferredAt: string
  }>>([])
  const { confirm } = useDialog()
  const { toast } = useToast()
  const { user } = useAuth()

  useEffect(() => {
    getBranches().then(b => { setBranches(b); setLoading(false) })
    const interval = setInterval(() => getBranches().then(setBranches), 30000)
    return () => clearInterval(interval)
  }, [])

  async function handleAdd(data: Omit<Branch, "id" | "createdAt" | "createdBy">) {
    setSaving(true)
    const b: Branch = { ...data, id: Date.now().toString(), createdAt: new Date().toISOString(), createdBy: user?.name || "system" }
    try {
      await saveBranch(b)
      setBranches(prev => [...prev, b])
      setAdding(false)
      toast({
        type: "success",
        title: "Branch Created",
        message: `${b.name} has been added successfully.`,
        duration: 3000,
      })
    } catch (error) {
      toast({
        type: "error",
        title: "Error",
        message: "Failed to create branch. Please try again.",
        duration: 5000,
      })
    } finally {
      setSaving(false)
    }
  }

  async function handleEdit(id: string, data: Omit<Branch, "id" | "createdAt" | "createdBy">) {
    setSaving(true)
    const existing = branches.find(b => b.id === id)
    const b: Branch = { ...data, id, createdAt: existing?.createdAt || new Date().toISOString(), createdBy: existing?.createdBy || user?.name || "system" }
    try {
      await saveBranch(b)
      setBranches(prev => prev.map(x => x.id === id ? b : x))
      setEditId(null)
      setViewBranch(b)
      toast({
        type: "success",
        title: "Branch Updated",
        message: `${b.name} has been updated successfully.`,
        duration: 3000,
      })
    } catch (error) {
      toast({
        type: "error",
        title: "Error",
        message: "Failed to update branch. Please try again.",
        duration: 5000,
      })
    } finally {
      setSaving(false)
    }
  }

  async function handleResetAllBranches() {
    const ok = await confirm({
      type: "confirm",
      title: "Reset all branch transfers",
      message:
        "Return all transferred inventory to the main warehouse and clear transfer history for every branch? This cannot be undone.",
      confirmLabel: "Reset everything",
    })
    if (!ok) return
    setResettingAll(true)
    try {
      await resetBranchInventory({ all: true })
      if (viewBranch) {
        setViewBranch(null)
      }
      toast({
        type: "success",
        title: "Reset complete",
        message: "All stock is back in the main warehouse and transfer history has been cleared.",
        duration: 4000,
      })
    } catch {
      toast({
        type: "error",
        title: "Reset failed",
        message: "Could not reset branch inventory and transfer history.",
        duration: 4000,
      })
    } finally {
      setResettingAll(false)
    }
  }

  async function handleDelete(id: string) {
    const ok = await confirm({
      type: "confirm",
      title: "Delete Branch",
      message: "This branch will be permanently removed.",
      confirmLabel: "Delete",
    })
    if (!ok) return
    await deleteBranch(id)
    setBranches(prev => prev.filter(b => b.id !== id))
    setViewBranch(null)
  }

  async function buildInventoryExportRows() {
    const targetBranches = branches.filter(b =>
      ["main_warehouse", "branch_warehouse", "warehouse", "store"].includes(b.type)
    )
    const rows = await Promise.all(
      targetBranches.map(async b => {
        const items = await getBranchInventory(b.id)
        return items.map(item => ({
          branchName: b.name,
          branchCode: b.code,
          branchType: b.type,
          item: item.productDescription || item.inventoryId,
          qty: item.quantity,
          unit: item.unit,
          transferredAt: item.assignedAt ? new Date(item.assignedAt).toLocaleDateString() : "-",
        }))
      })
    )
    return rows.flat()
  }

  async function handleOpenExportPreview() {
    setExportLoading(true)
    try {
      const rows = await buildInventoryExportRows()
      setExportRows(rows)
      setExportPreviewOpen(true)
    } finally {
      setExportLoading(false)
    }
  }

  async function handleExportPdf() {
    const rows = exportRows.length ? exportRows : await buildInventoryExportRows()
    const [{ default: jsPDF }, autoTableModule] = await Promise.all([
      import("jspdf"),
      import("jspdf-autotable"),
    ])
    const autoTable = (autoTableModule as any).default || autoTableModule
    const doc = new jsPDF("p", "mm", "a4")
    doc.setFontSize(14)
    doc.text("Warehouse and Store Inventory Report", 14, 16)
    doc.setFontSize(10)
    doc.text(`Generated: ${new Date().toLocaleString()}`, 14, 22)
    autoTable(doc, {
      startY: 26,
      head: [["Branch", "Code", "Type", "Item", "Qty", "Unit", "Transferred/Added Date"]],
      body: rows.map(r => [r.branchName, r.branchCode, r.branchType, r.item, String(r.qty), r.unit, r.transferredAt]),
      styles: { fontSize: 8, cellPadding: 2 },
      headStyles: { fillColor: [31, 172, 166] },
    })
    doc.save(`branch-inventory-report-${new Date().toISOString().slice(0, 10)}.pdf`)
  }

  const editingBranch = branches.find(b => b.id === editId)

  return (
    <div className="p-6 space-y-2">
      {loading ? (
        <div className="flex flex-col items-center justify-center py-24 gap-3">
          <Loader2 className="h-6 w-6 animate-spin text-[hsl(var(--muted-foreground))]" />
          <p className="text-sm text-[hsl(var(--muted-foreground))]">Loading branches...</p>
        </div>
      ) : (
        <>
          <div className="space-y-0 my-4">
            {/* Action buttons */}
            <div className="flex items-center justify-end gap-2">
              <Button
                size="sm"
                variant="outline"
                className="h-8 text-xs cursor-pointer text-red-600 border-red-300 hover:bg-red-50"
                onClick={handleResetAllBranches}
                disabled={resettingAll}
              >
                {resettingAll ? <Loader2 className="h-3.5 w-3.5 animate-spin" /> : <Trash2 className="h-3.5 w-3.5" />}
                Reset all transfers
              </Button>
              <Button
                size="sm"
                variant="outline"
                className="h-8 text-xs cursor-pointer"
                onClick={handleOpenExportPreview}
                disabled={exportLoading}
              >
                {exportLoading ? <Loader2 className="h-3.5 w-3.5 animate-spin" /> : <FileDown className="h-3.5 w-3.5" />}
                Export Inventory PDF
              </Button>
              <Button size="sm" className="h-8 text-xs cursor-pointer bg-[#1faca6] hover:bg-[#17857f] text-white" onClick={async () => {
                const code = await generateBranchCode()
                setAutoCode(code)
                setAdding(true)
                setEditId(null)
              }}>
                <Plus className="h-3.5 w-3.5" /> Add Branch
              </Button>
            </div>
          </div>

          {/* Empty */}
          {branches.length === 0 && !adding && (
            <div className="flex flex-col items-center justify-center py-24 text-center gap-2">
              <p className="text-sm font-medium">No branches yet</p>
              <p className="text-xs text-[hsl(var(--muted-foreground))]">Add your first branch using the button above.</p>
            </div>
          )}

          {/* List */}
          {branches.length > 0 && (
            <div className="rounded-lg border overflow-hidden">
              <table className="w-full text-sm">
            <thead>
              <tr className="border-b bg-[hsl(var(--muted))]/40">
                {["Name", "Code", "Type", "Manager", "Status", "Actions"].map(h => (
                  <th key={h} className="h-9 px-4 text-left text-[10px] font-semibold uppercase tracking-wide text-[hsl(var(--muted-foreground))]">{h === "Actions" ? "" : h}</th>
                ))}
              </tr>
            </thead>
            <tbody className="divide-y">
              {branches.map(b => (
                <tr key={b.id}
                  onClick={() => { setViewBranch(b); setEditId(null) }}
                  className="hover:bg-[hsl(var(--muted))]/20 transition-colors cursor-pointer">
                  <td className="px-4 py-2.5 font-medium text-[hsl(var(--primary))]">{b.name}</td>
                  <td className="px-4 py-2.5 text-xs text-[hsl(var(--muted-foreground))]">{b.code}</td>
                  <td className="px-4 py-2.5">
                    <Badge variant="info" className="text-[10px] px-1.5 py-0">
                      {b.type === "main_warehouse" ? "main warehouse" : b.type === "branch_warehouse" ? "branch warehouse" : b.type}
                    </Badge>
                  </td>
                  <td className="px-4 py-2.5 text-xs text-[hsl(var(--muted-foreground))]">{b.manager || "—"}</td>
                  <td className="px-4 py-2.5">
                    <Badge variant={b.status === "active" ? "success" : "secondary"} className="text-[10px] px-1.5 py-0">{b.status}</Badge>
                  </td>
                  <td className="px-4 py-2.5 flex items-center gap-1">
                    <Button 
                      variant="ghost" 
                      size="icon" 
                      className="h-7 w-7 text-[#1faca6] hover:text-[#17857f] hover:bg-[#1faca6]/10"
                      title="Export Inventory PDF"
                      onClick={async (e) => {
                        e.stopPropagation()
                        const inv = await getBranchInventory(b.id)
                        generateSingleBranchPdf(b, inv)
                      }}
                    >
                      <FileDown className="h-3.5 w-3.5" />
                    </Button>
                    <Button variant="ghost" size="icon" className="h-7 w-7 text-[hsl(var(--muted-foreground))] hover:text-red-500 hover:bg-red-50"
                      onClick={e => { e.stopPropagation(); handleDelete(b.id) }}>
                      <Trash2 className="h-3.5 w-3.5" />
                    </Button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}
        </>
      )}

      {/* Add modal */}
      {adding && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 backdrop-blur-sm p-4" onClick={() => setAdding(false)}>
          <div className="w-full max-w-lg rounded-xl border bg-[hsl(var(--card))] shadow-xl overflow-hidden" onClick={e => e.stopPropagation()}>
            <div className="flex items-center justify-between px-5 py-4 border-b">
              <p className="text-sm font-semibold">Add Branch</p>
              <Button variant="ghost" size="icon" className="h-7 w-7" onClick={() => setAdding(false)}>
                <X className="h-4 w-4" />
              </Button>
            </div>
            <div className="p-5">
              <BranchForm initial={empty(autoCode)} onSave={handleAdd} onCancel={() => setAdding(false)} isLoading={saving} autoGenerated={!!autoCode} />
            </div>
          </div>
        </div>
      )}

      {/* Edit modal */}
      {editId && editingBranch && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 backdrop-blur-sm p-4" onClick={() => setEditId(null)}>
          <div className="w-full max-w-lg rounded-xl border bg-[hsl(var(--card))] shadow-xl p-6 space-y-4" onClick={e => e.stopPropagation()}>
            <div className="flex items-center justify-between">
              <p className="text-sm font-semibold">Edit Branch</p>
              <Button variant="ghost" size="icon" className="h-7 w-7" onClick={() => setEditId(null)}>
                <X className="h-4 w-4" />
              </Button>
            </div>
            <BranchForm
              initial={{ name: editingBranch.name, code: editingBranch.code, type: editingBranch.type, address: editingBranch.address, city: editingBranch.city, country: editingBranch.country, phone: editingBranch.phone, email: editingBranch.email, manager: editingBranch.manager, status: editingBranch.status, notes: editingBranch.notes }}
              onSave={data => handleEdit(editId, data)}
              onCancel={() => setEditId(null)}
              isLoading={saving}
              autoGenerated={false}
            />
          </div>
        </div>
      )}

      {exportPreviewOpen && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 backdrop-blur-sm p-4" onClick={() => setExportPreviewOpen(false)}>
          <div className="w-full max-w-5xl rounded-xl border bg-[hsl(var(--card))] shadow-xl overflow-hidden" onClick={e => e.stopPropagation()}>
            <div className="flex items-center justify-between px-5 py-4 border-b">
              <p className="text-sm font-semibold">Inventory Export Preview</p>
              <Button variant="ghost" size="icon" className="h-7 w-7" onClick={() => setExportPreviewOpen(false)}>
                <X className="h-4 w-4" />
              </Button>
            </div>
            <div className="p-5">
              {exportRows.length === 0 ? (
                <p className="text-xs text-[hsl(var(--muted-foreground))]">No inventory rows found for warehouses/stores.</p>
              ) : (
                <div className="max-h-[55vh] overflow-auto rounded-md border">
                  <table className="w-full text-xs">
                    <thead className="bg-[hsl(var(--muted))]/40 sticky top-0">
                      <tr>
                        {["Branch", "Code", "Type", "Item", "Qty", "Unit", "Transferred/Added Date"].map(h => (
                          <th key={h} className="px-3 py-2 text-left font-semibold">{h}</th>
                        ))}
                      </tr>
                    </thead>
                    <tbody>
                      {exportRows.map((row, index) => (
                        <tr key={`${row.branchCode}-${row.item}-${index}`} className="border-t">
                          <td className="px-3 py-2">{row.branchName}</td>
                          <td className="px-3 py-2">{row.branchCode}</td>
                          <td className="px-3 py-2">{row.branchType}</td>
                          <td className="px-3 py-2">{row.item}</td>
                          <td className="px-3 py-2">{row.qty}</td>
                          <td className="px-3 py-2">{row.unit}</td>
                          <td className="px-3 py-2">{row.transferredAt}</td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              )}
            </div>
            <div className="px-5 py-3 border-t flex justify-end gap-2 bg-[hsl(var(--muted))]/20">
              <Button size="sm" variant="outline" className="h-8 text-xs cursor-pointer" onClick={() => setExportPreviewOpen(false)}>
                Close
              </Button>
              <Button size="sm" className="h-8 text-xs cursor-pointer bg-[#1faca6] hover:bg-[#17857f] text-white" onClick={handleExportPdf}>
                <FileDown className="h-3.5 w-3.5" />
                Export PDF
              </Button>
            </div>
          </div>
        </div>
      )}

      {/* Detail popup */}
      {viewBranch && !editId && (
        <BranchDetail
          branch={viewBranch}
          branches={branches}
          onClose={() => setViewBranch(null)}
          onEdit={() => { setEditId(viewBranch.id); setViewBranch(null) }}
          onDelete={() => handleDelete(viewBranch.id)}
        />
      )}
    </div>
  )
}
