"use client"
import { useState, useEffect } from "react"
import { getBranches, saveBranch, deleteBranch, generateBranchCode, getBranchInventory, assignInventoryToBranch, removeBranchInventory, type Branch, type BranchInventory } from "@/lib/branches"
import { Package } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Badge } from "@/components/ui/badge"
import { Plus, Pencil, Trash2, X, Phone, Mail, MapPin, Building2, Loader2, User } from "lucide-react"
import { useDialog } from "@/components/ui/dialog-provider"
import { useToast } from "@/components/ui/toast"
import { useAuth } from "@/components/auth-provider"

const empty = (code: string = ""): Omit<Branch, "id" | "createdAt" | "createdBy"> => ({
  name: "", code, type: "outlet", address: "", city: "", country: "", phone: "", email: "", manager: "", status: "active", notes: "",
})

// ── Branch Form ────────────────────────────────────────────────
function BranchForm({ initial, onSave, onCancel, isLoading, autoGenerated }: {
  initial: Omit<Branch, "id" | "createdAt" | "createdBy">
  onSave: (b: Omit<Branch, "id" | "createdAt" | "createdBy">) => void
  onCancel: () => void
  isLoading?: boolean
  autoGenerated?: boolean
}) {
  const [form, setForm] = useState(initial)
  const set = (k: keyof typeof form, v: string) => setForm(f => ({ ...f, [k]: v }))

  return (
    <form onSubmit={e => { e.preventDefault(); onSave(form) }}
      className="border rounded-lg p-4 space-y-3 bg-[hsl(var(--muted))]/20">
      <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
        <div className="space-y-1 sm:col-span-2">
          <label className="text-xs font-medium">Branch Name *</label>
          <input required value={form.name} onChange={e => set("name", e.target.value)}
            placeholder="e.g. Main Outlet"
            className="w-full h-8 rounded-md border bg-[hsl(var(--background))] px-3 text-sm focus:outline-none focus:ring-1 focus:ring-[hsl(var(--ring))]" />
        </div>
        <div className="space-y-1">
          <label className="text-xs font-medium">Branch Code *</label>
          <input required value={form.code} onChange={e => set("code", e.target.value)}
            placeholder="e.g. BR001"
            readOnly={autoGenerated}
            className={`w-full h-8 rounded-md border bg-[hsl(var(--background))] px-3 text-sm focus:outline-none focus:ring-1 focus:ring-[hsl(var(--ring))] ${autoGenerated ? "bg-[hsl(var(--muted))]/50 cursor-not-allowed" : ""}`}
          />
          {autoGenerated && <p className="text-[10px] text-[hsl(var(--muted-foreground))]">Auto-generated</p>}
        </div>
        <div className="space-y-1">
          <label className="text-xs font-medium">Type *</label>
          <select required value={form.type} onChange={e => set("type", e.target.value)}
            className="w-full h-8 rounded-md border bg-[hsl(var(--background))] px-3 text-sm focus:outline-none focus:ring-1 focus:ring-[hsl(var(--ring))]">
            <option value="outlet">Outlet</option>
            <option value="store">Store</option>
            <option value="warehouse">Warehouse</option>
            <option value="office">Office</option>
          </select>
        </div>
        <div className="space-y-1">
          <label className="text-xs font-medium">Manager</label>
          <input value={form.manager} onChange={e => set("manager", e.target.value)}
            placeholder="Manager name"
            className="w-full h-8 rounded-md border bg-[hsl(var(--background))] px-3 text-sm focus:outline-none focus:ring-1 focus:ring-[hsl(var(--ring))]" />
        </div>
        <div className="space-y-1">
          <label className="text-xs font-medium">Status *</label>
          <select required value={form.status} onChange={e => set("status", e.target.value)}
            className="w-full h-8 rounded-md border bg-[hsl(var(--background))] px-3 text-sm focus:outline-none focus:ring-1 focus:ring-[hsl(var(--ring))]">
            <option value="active">Active</option>
            <option value="inactive">Inactive</option>
          </select>
        </div>
        <div className="space-y-1">
          <label className="text-xs font-medium">Phone</label>
          <input value={form.phone} onChange={e => set("phone", e.target.value)}
            placeholder="+92 300 0000000"
            className="w-full h-8 rounded-md border bg-[hsl(var(--background))] px-3 text-sm focus:outline-none focus:ring-1 focus:ring-[hsl(var(--ring))]" />
        </div>
        <div className="space-y-1">
          <label className="text-xs font-medium">Email</label>
          <input type="email" value={form.email} onChange={e => set("email", e.target.value)}
            className="w-full h-8 rounded-md border bg-[hsl(var(--background))] px-3 text-sm focus:outline-none focus:ring-1 focus:ring-[hsl(var(--ring))]" />
        </div>
        <div className="space-y-1">
          <label className="text-xs font-medium">City</label>
          <input value={form.city} onChange={e => set("city", e.target.value)}
            className="w-full h-8 rounded-md border bg-[hsl(var(--background))] px-3 text-sm focus:outline-none focus:ring-1 focus:ring-[hsl(var(--ring))]" />
        </div>
        <div className="space-y-1 sm:col-span-2">
          <label className="text-xs font-medium">Address</label>
          <input value={form.address} onChange={e => set("address", e.target.value)}
            className="w-full h-8 rounded-md border bg-[hsl(var(--background))] px-3 text-sm focus:outline-none focus:ring-1 focus:ring-[hsl(var(--ring))]" />
        </div>
        <div className="space-y-1">
          <label className="text-xs font-medium">Country</label>
          <input value={form.country} onChange={e => set("country", e.target.value)}
            className="w-full h-8 rounded-md border bg-[hsl(var(--background))] px-3 text-sm focus:outline-none focus:ring-1 focus:ring-[hsl(var(--ring))]" />
        </div>
        <div className="space-y-1 sm:col-span-2">
          <label className="text-xs font-medium">Notes</label>
          <textarea value={form.notes} onChange={e => set("notes", e.target.value)} rows={2}
            className="w-full rounded-md border bg-[hsl(var(--background))] px-3 py-2 text-sm focus:outline-none focus:ring-1 focus:ring-[hsl(var(--ring))] resize-none" />
        </div>
      </div>
      <div className="flex gap-2">
        <Button type="submit" size="sm" className="h-8 cursor-pointer" disabled={isLoading}>
          {isLoading ? (
            <>
              <Loader2 className="h-3.5 w-3.5 animate-spin mr-1" />
              Saving...
            </>
          ) : (
            "Save Branch"
          )}
        </Button>
        <Button type="button" variant="outline" size="sm" className="h-8 cursor-pointer" onClick={onCancel} disabled={isLoading}>Cancel</Button>
      </div>
    </form>
  )
}

// ── Branch Detail Popup ────────────────────────────────────────
function BranchDetail({ branch, onClose, onEdit, onDelete }: {
  branch: Branch
  onClose: () => void
  onEdit: () => void
  onDelete: () => void
}) {
  const [inventory, setInventory] = useState<BranchInventory[]>([])
  const [loadingInventory, setLoadingInventory] = useState(true)
  const [showAddInventory, setShowAddInventory] = useState(false)
  const [systemInventory, setSystemInventory] = useState<any[]>([])
  const [loadingSystemInventory, setLoadingSystemInventory] = useState(false)
  const [selectedInventoryId, setSelectedInventoryId] = useState("")
  const [quantity, setQuantity] = useState("")
  const [assigning, setAssigning] = useState(false)
  const { toast } = useToast()
  const { user } = useAuth()

  useEffect(() => {
    getBranchInventory(branch.id).then(data => {
      setInventory(data)
      setLoadingInventory(false)
    })
  }, [branch.id])

  async function loadSystemInventory() {
    setLoadingSystemInventory(true)
    try {
      const res = await fetch("/api/db/inventory-stock")
      if (res.ok) {
        const data = await res.json()
        setSystemInventory(data)
      }
    } catch {
      setSystemInventory([])
    } finally {
      setLoadingSystemInventory(false)
    }
  }

  async function handleShowAddInventory() {
    setShowAddInventory(true)
    await loadSystemInventory()
  }

  async function handleAssignInventory() {
    if (!selectedInventoryId || !quantity) {
      toast({
        type: "error",
        title: "Error",
        message: "Please select an inventory item and enter a quantity.",
        duration: 3000,
      })
      return
    }

    const qty = parseFloat(quantity)
    if (isNaN(qty) || qty <= 0) {
      toast({
        type: "error",
        title: "Error",
        message: "Please enter a valid quantity.",
        duration: 3000,
      })
      return
    }

    const selectedItem = systemInventory.find(i => i.id === selectedInventoryId)
    if (!selectedItem) return

    setAssigning(true)
    try {
      await assignInventoryToBranch({
        branchId: branch.id,
        inventoryId: selectedInventoryId,
        quantity: qty,
        unit: selectedItem.unit || "",
        branchCode: branch.code,
        assignedBy: user?.name || "system",
        notes: ""
      })

      // Refresh branch inventory
      const updatedInventory = await getBranchInventory(branch.id)
      setInventory(updatedInventory)

      setShowAddInventory(false)
      setSelectedInventoryId("")
      setQuantity("")
      toast({
        type: "success",
        title: "Inventory Assigned",
        message: `${qty} ${selectedItem.unit} of ${selectedItem.description} has been assigned to ${branch.name}.`,
        duration: 3000,
      })
    } catch {
      toast({
        type: "error",
        title: "Error",
        message: "Failed to assign inventory. Please try again.",
        duration: 3000,
      })
    } finally {
      setAssigning(false)
    }
  }

  async function handleRemoveInventory(id: string) {
    await removeBranchInventory(id)
    setInventory(prev => prev.filter(i => i.id !== id))
    toast({
      type: "success",
      title: "Inventory Removed",
      message: "Inventory has been removed from the branch.",
      duration: 3000,
    })
  }

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 backdrop-blur-sm p-4" onClick={onClose}>
      <div className="w-full max-w-md rounded-2xl border bg-[hsl(var(--card))] shadow-2xl overflow-hidden" onClick={e => e.stopPropagation()}>
        {/* Header */}
        <div className="px-6 pt-6 pb-4">
          <div className="flex items-start justify-between">
            <div className="flex items-center gap-4">
              <div className="flex h-16 w-16 items-center justify-center rounded-full bg-[#1faca6] text-2xl font-bold text-white shadow-sm">
                {branch.name.charAt(0).toUpperCase()}
              </div>
              <div>
                <p className="text-lg font-semibold">{branch.name}</p>
                <p className="text-sm text-[hsl(var(--muted-foreground))] mt-0.5">{branch.code}</p>
                <div className="mt-2">
                  <Badge variant={branch.status === "active" ? "success" : "secondary"} className="text-[10px] px-2 py-0.5">
                    {branch.status}
                  </Badge>
                  <Badge variant="info" className="text-[10px] px-2 py-0.5 ml-1">
                    {branch.type}
                  </Badge>
                </div>
              </div>
            </div>
            <Button variant="ghost" size="icon" className="h-8 w-8 -mt-1 -mr-2 cursor-pointer" onClick={onClose}>
              <X className="h-4 w-4" />
            </Button>
          </div>
        </div>

        {/* Details */}
        <div className="px-6 pb-4 space-y-2.5">
          {branch.manager && (
            <div className="flex items-center gap-3 p-2.5 rounded-lg bg-[hsl(var(--muted))]/30">
              <div className="flex h-8 w-8 shrink-0 items-center justify-center rounded-lg bg-[hsl(var(--background))]">
                <User className="h-4 w-4 text-[hsl(var(--muted-foreground))]" />
              </div>
              <div className="min-w-0">
                <p className="text-[10px] text-[hsl(var(--muted-foreground))] uppercase tracking-wider font-medium">Manager</p>
                <p className="text-sm font-medium truncate">{branch.manager}</p>
              </div>
            </div>
          )}
          {branch.phone && (
            <div className="flex items-center gap-3 p-2.5 rounded-lg bg-[hsl(var(--muted))]/30">
              <div className="flex h-8 w-8 shrink-0 items-center justify-center rounded-lg bg-[hsl(var(--background))]">
                <Phone className="h-4 w-4 text-[hsl(var(--muted-foreground))]" />
              </div>
              <div className="min-w-0">
                <p className="text-[10px] text-[hsl(var(--muted-foreground))] uppercase tracking-wider font-medium">Phone</p>
                <p className="text-sm font-medium truncate">{branch.phone}</p>
              </div>
            </div>
          )}
          {branch.email && (
            <div className="flex items-center gap-3 p-2.5 rounded-lg bg-[hsl(var(--muted))]/30">
              <div className="flex h-8 w-8 shrink-0 items-center justify-center rounded-lg bg-[hsl(var(--background))]">
                <Mail className="h-4 w-4 text-[hsl(var(--muted-foreground))]" />
              </div>
              <div className="min-w-0">
                <p className="text-[10px] text-[hsl(var(--muted-foreground))] uppercase tracking-wider font-medium">Email</p>
                <p className="text-sm font-medium truncate">{branch.email}</p>
              </div>
            </div>
          )}
          {(branch.address || branch.city) && (
            <div className="flex items-start gap-3 p-2.5 rounded-lg bg-[hsl(var(--muted))]/30">
              <div className="flex h-8 w-8 shrink-0 items-center justify-center rounded-lg bg-[hsl(var(--background))]">
                <MapPin className="h-4 w-4 text-[hsl(var(--muted-foreground))]" />
              </div>
              <div className="min-w-0">
                <p className="text-[10px] text-[hsl(var(--muted-foreground))] uppercase tracking-wider font-medium">Address</p>
                <p className="text-sm font-medium leading-snug">{branch.address}{branch.city && `, ${branch.city}`}{branch.country && `, ${branch.country}`}</p>
              </div>
            </div>
          )}
          {branch.notes && (
            <div className="border-t pt-2.5 mt-1">
              <div className="flex items-start gap-3 p-2.5 rounded-lg bg-[hsl(var(--muted))]/30">
                <div className="min-w-0">
                  <p className="text-[10px] text-[hsl(var(--muted-foreground))] uppercase tracking-wider font-medium">Notes</p>
                  <p className="text-sm font-medium">{branch.notes}</p>
                </div>
              </div>
            </div>
          )}

          {/* Inventory Section */}
          <div className="border-t pt-2.5 mt-1">
            <div className="flex items-center justify-between mb-2">
              <p className="text-[10px] text-[hsl(var(--muted-foreground))] uppercase tracking-wider font-medium">Branch Inventory</p>
              <Button size="sm" variant="outline" className="h-6 text-[10px] cursor-pointer" onClick={handleShowAddInventory}>
                <Plus className="h-3 w-3" /> Add
              </Button>
            </div>
            {loadingInventory ? (
              <div className="flex items-center justify-center py-4">
                <Loader2 className="h-4 w-4 animate-spin text-[hsl(var(--muted-foreground))]" />
              </div>
            ) : inventory.length === 0 ? (
              <p className="text-xs text-[hsl(var(--muted-foreground))] py-2">No inventory assigned to this branch.</p>
            ) : (
              <div className="space-y-1.5 max-h-32 overflow-y-auto">
                {inventory.map(inv => (
                  <div key={inv.id} className="flex items-center justify-between p-2 rounded bg-[hsl(var(--muted))]/30">
                    <div className="flex-1 min-w-0">
                      <p className="text-xs font-medium truncate">{inv.productDescription || inv.inventoryId}</p>
                      <p className="text-[10px] text-[hsl(var(--muted-foreground))]">{inv.quantity} {inv.unit}</p>
                    </div>
                    <Button variant="ghost" size="icon" className="h-5 w-5 text-[hsl(var(--muted-foreground))] hover:text-red-500"
                      onClick={() => handleRemoveInventory(inv.id)}>
                      <Trash2 className="h-3 w-3" />
                    </Button>
                  </div>
                ))}
              </div>
            )}
          </div>
        </div>

        {/* Footer */}
        <div className="flex items-center gap-2 px-6 py-4 border-t bg-[hsl(var(--muted))]/20">
          <Button size="sm" variant="outline" className="h-9 text-xs cursor-pointer" onClick={onEdit}>
            <Pencil className="h-3.5 w-3.5" /> Edit
          </Button>
          <Button size="sm" variant="ghost" className="h-9 text-xs text-red-500 hover:text-red-600 hover:bg-red-50 cursor-pointer" onClick={onDelete}>
            <Trash2 className="h-3.5 w-3.5" /> Delete
          </Button>
          <Button size="sm" variant="ghost" className="h-9 text-xs ml-auto cursor-pointer" onClick={onClose}>Close</Button>
        </div>
      </div>

      {/* Add Inventory Modal */}
      {showAddInventory && (
        <div className="fixed inset-0 z-[60] flex items-center justify-center bg-black/40 backdrop-blur-sm p-4" onClick={() => setShowAddInventory(false)}>
          <div className="w-full max-w-md rounded-xl border bg-[hsl(var(--card))] shadow-xl overflow-hidden" onClick={e => e.stopPropagation()}>
            <div className="flex items-center justify-between px-5 py-4 border-b">
              <p className="text-sm font-semibold">Assign Inventory</p>
              <Button variant="ghost" size="icon" className="h-7 w-7" onClick={() => setShowAddInventory(false)}>
                <X className="h-4 w-4" />
              </Button>
            </div>
            <div className="p-5 space-y-4">
              <p className="text-xs text-[hsl(var(--muted-foreground))]">Select inventory from the system to assign to this branch. The quantity will be deducted from the main inventory.</p>
              
              {loadingSystemInventory ? (
                <div className="flex items-center justify-center py-8">
                  <Loader2 className="h-5 w-5 animate-spin text-[hsl(var(--muted-foreground))]" />
                </div>
              ) : systemInventory.length === 0 ? (
                <p className="text-xs text-[hsl(var(--muted-foreground))] py-4 text-center">No inventory available in the system.</p>
              ) : (
                <>
                  <div className="space-y-1">
                    <label className="text-xs font-medium">Select Inventory Item</label>
                    <select
                      value={selectedInventoryId}
                      onChange={e => setSelectedInventoryId(e.target.value)}
                      className="w-full h-9 rounded-md border bg-[hsl(var(--background))] px-3 text-sm focus:outline-none focus:ring-1 focus:ring-[hsl(var(--ring))]"
                    >
                      <option value="">-- Select an item --</option>
                      {systemInventory.map(item => (
                        <option key={item.id} value={item.id}>
                          {item.description} (Available: {item.availableQty} {item.unit})
                        </option>
                      ))}
                    </select>
                  </div>

                  <div className="space-y-1">
                    <label className="text-xs font-medium">Quantity</label>
                    <input
                      type="number"
                      value={quantity}
                      onChange={e => setQuantity(e.target.value)}
                      placeholder="Enter quantity"
                      className="w-full h-9 rounded-md border bg-[hsl(var(--background))] px-3 text-sm focus:outline-none focus:ring-1 focus:ring-[hsl(var(--ring))]"
                    />
                  </div>

                  {selectedInventoryId && (
                    <div className="flex items-start gap-2 p-2 rounded bg-[hsl(var(--muted))]/30">
                      <Package className="h-4 w-4 text-[hsl(var(--muted-foreground))] mt-0.5" />
                      <div className="flex-1 min-w-0">
                        <p className="text-xs font-medium truncate">{systemInventory.find(i => i.id === selectedInventoryId)?.description}</p>
                        <p className="text-[10px] text-[hsl(var(--muted-foreground))]">Available: {systemInventory.find(i => i.id === selectedInventoryId)?.availableQty} {systemInventory.find(i => i.id === selectedInventoryId)?.unit}</p>
                      </div>
                    </div>
                  )}

                  <Button
                    size="sm"
                    className="w-full cursor-pointer bg-[#1faca6] hover:bg-[#17857f] text-white"
                    onClick={handleAssignInventory}
                    disabled={assigning || !selectedInventoryId || !quantity}
                  >
                    {assigning ? (
                      <>
                        <Loader2 className="h-3.5 w-3.5 animate-spin mr-1" />
                        Assigning...
                      </>
                    ) : (
                      "Assign Inventory"
                    )}
                  </Button>
                </>
              )}
            </div>
          </div>
        </div>
      )}
    </div>
  )
}

// ── Main Tab ─────────────────────────────────────────────────────
export function BranchesTab() {
  const [branches, setBranches] = useState<Branch[]>([])
  const [loading, setLoading] = useState(true)
  const [adding, setAdding] = useState(false)
  const [editId, setEditId] = useState<string | null>(null)
  const [viewBranch, setViewBranch] = useState<Branch | null>(null)
  const [saving, setSaving] = useState(false)
  const [autoCode, setAutoCode] = useState("")
  const { confirm } = useDialog()
  const { toast } = useToast()
  const { user } = useAuth()

  useEffect(() => {
    getBranches().then(b => { setBranches(b); setLoading(false) })
    const interval = setInterval(() => getBranches().then(setBranches), 30000)
    return () => clearInterval(interval)
  }, [])

  async function handleAdd(data: Omit<Branch, "id" | "createdAt" | "createdBy">) {
    setSaving(true)
    const b: Branch = { ...data, id: Date.now().toString(), createdAt: new Date().toISOString(), createdBy: user?.name || "system" }
    try {
      await saveBranch(b)
      setBranches(prev => [...prev, b])
      setAdding(false)
      toast({
        type: "success",
        title: "Branch Created",
        message: `${b.name} has been added successfully.`,
        duration: 3000,
      })
    } catch (error) {
      toast({
        type: "error",
        title: "Error",
        message: "Failed to create branch. Please try again.",
        duration: 5000,
      })
    } finally {
      setSaving(false)
    }
  }

  async function handleEdit(id: string, data: Omit<Branch, "id" | "createdAt" | "createdBy">) {
    setSaving(true)
    const existing = branches.find(b => b.id === id)
    const b: Branch = { ...data, id, createdAt: existing?.createdAt || new Date().toISOString(), createdBy: existing?.createdBy || user?.name || "system" }
    try {
      await saveBranch(b)
      setBranches(prev => prev.map(x => x.id === id ? b : x))
      setEditId(null)
      setViewBranch(b)
      toast({
        type: "success",
        title: "Branch Updated",
        message: `${b.name} has been updated successfully.`,
        duration: 3000,
      })
    } catch (error) {
      toast({
        type: "error",
        title: "Error",
        message: "Failed to update branch. Please try again.",
        duration: 5000,
      })
    } finally {
      setSaving(false)
    }
  }

  async function handleDelete(id: string) {
    const ok = await confirm({
      type: "confirm",
      title: "Delete Branch",
      message: "This branch will be permanently removed.",
      confirmLabel: "Delete",
    })
    if (!ok) return
    await deleteBranch(id)
    setBranches(prev => prev.filter(b => b.id !== id))
    setViewBranch(null)
  }

  const editingBranch = branches.find(b => b.id === editId)

  return (
    <div className="p-6 space-y-2">
      {loading ? (
        <div className="flex flex-col items-center justify-center py-24 gap-3">
          <Loader2 className="h-6 w-6 animate-spin text-[hsl(var(--muted-foreground))]" />
          <p className="text-sm text-[hsl(var(--muted-foreground))]">Loading branches...</p>
        </div>
      ) : (
        <>
          <div className="space-y-0 my-4">
            {/* Action buttons */}
            <div className="flex items-center justify-end">
              <Button size="sm" className="h-8 text-xs cursor-pointer bg-[#1faca6] hover:bg-[#17857f] text-white" onClick={async () => {
                const code = await generateBranchCode()
                setAutoCode(code)
                setAdding(true)
                setEditId(null)
              }}>
                <Plus className="h-3.5 w-3.5" /> Add Branch
              </Button>
            </div>
          </div>

          {/* Empty */}
          {branches.length === 0 && !adding && (
            <div className="flex flex-col items-center justify-center py-24 text-center gap-2">
              <p className="text-sm font-medium">No branches yet</p>
              <p className="text-xs text-[hsl(var(--muted-foreground))]">Add your first branch using the button above.</p>
            </div>
          )}

          {/* List */}
          {branches.length > 0 && (
            <div className="rounded-lg border overflow-hidden">
              <table className="w-full text-sm">
            <thead>
              <tr className="border-b bg-[hsl(var(--muted))]/40">
                {["Name", "Code", "Type", "Manager", "Status", ""].map(h => (
                  <th key={h} className="h-9 px-4 text-left text-[10px] font-semibold uppercase tracking-wide text-[hsl(var(--muted-foreground))]">{h}</th>
                ))}
              </tr>
            </thead>
            <tbody className="divide-y">
              {branches.map(b => (
                <tr key={b.id}
                  onClick={() => { setViewBranch(b); setEditId(null) }}
                  className="hover:bg-[hsl(var(--muted))]/20 transition-colors cursor-pointer">
                  <td className="px-4 py-2.5 font-medium text-[hsl(var(--primary))]">{b.name}</td>
                  <td className="px-4 py-2.5 text-xs text-[hsl(var(--muted-foreground))]">{b.code}</td>
                  <td className="px-4 py-2.5">
                    <Badge variant="info" className="text-[10px] px-1.5 py-0">{b.type}</Badge>
                  </td>
                  <td className="px-4 py-2.5 text-xs text-[hsl(var(--muted-foreground))]">{b.manager || "—"}</td>
                  <td className="px-4 py-2.5">
                    <Badge variant={b.status === "active" ? "success" : "secondary"} className="text-[10px] px-1.5 py-0">{b.status}</Badge>
                  </td>
                  <td className="px-4 py-2.5">
                    <Button variant="ghost" size="icon" className="h-6 w-6 text-[hsl(var(--muted-foreground))] hover:text-red-500"
                      onClick={e => { e.stopPropagation(); handleDelete(b.id) }}>
                      <Trash2 className="h-3.5 w-3.5" />
                    </Button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}
        </>
      )}

      {/* Add modal */}
      {adding && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 backdrop-blur-sm p-4" onClick={() => setAdding(false)}>
          <div className="w-full max-w-lg rounded-xl border bg-[hsl(var(--card))] shadow-xl overflow-hidden" onClick={e => e.stopPropagation()}>
            <div className="flex items-center justify-between px-5 py-4 border-b">
              <p className="text-sm font-semibold">Add Branch</p>
              <Button variant="ghost" size="icon" className="h-7 w-7" onClick={() => setAdding(false)}>
                <X className="h-4 w-4" />
              </Button>
            </div>
            <div className="p-5">
              <BranchForm initial={empty(autoCode)} onSave={handleAdd} onCancel={() => setAdding(false)} isLoading={saving} autoGenerated={!!autoCode} />
            </div>
          </div>
        </div>
      )}

      {/* Edit modal */}
      {editId && editingBranch && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 backdrop-blur-sm p-4" onClick={() => setEditId(null)}>
          <div className="w-full max-w-lg rounded-xl border bg-[hsl(var(--card))] shadow-xl p-6 space-y-4" onClick={e => e.stopPropagation()}>
            <div className="flex items-center justify-between">
              <p className="text-sm font-semibold">Edit Branch</p>
              <Button variant="ghost" size="icon" className="h-7 w-7" onClick={() => setEditId(null)}>
                <X className="h-4 w-4" />
              </Button>
            </div>
            <BranchForm
              initial={{ name: editingBranch.name, code: editingBranch.code, type: editingBranch.type, address: editingBranch.address, city: editingBranch.city, country: editingBranch.country, phone: editingBranch.phone, email: editingBranch.email, manager: editingBranch.manager, status: editingBranch.status, notes: editingBranch.notes }}
              onSave={data => handleEdit(editId, data)}
              onCancel={() => setEditId(null)}
              isLoading={saving}
              autoGenerated={false}
            />
          </div>
        </div>
      )}

      {/* Detail popup */}
      {viewBranch && !editId && (
        <BranchDetail
          branch={viewBranch}
          onClose={() => setViewBranch(null)}
          onEdit={() => { setEditId(viewBranch.id); setViewBranch(null) }}
          onDelete={() => handleDelete(viewBranch.id)}
        />
      )}
    </div>
  )
}
