  "use client"
import { useState, useEffect } from "react"
import { getBranches, saveBranch, deleteBranch, generateBranchCode, getBranchInventory, resetBranchInventory, type Branch } from "@/lib/branches"
import { BranchDetailView } from "@/components/branches/branch-detail-view"
import { Button } from "@/components/ui/button"
import { Badge } from "@/components/ui/badge"
import { Plus, Trash2, X, Loader2, FileDown, Building2, ChevronRight } from "lucide-react"
import { useDialog } from "@/components/ui/dialog-provider"
import { useToast } from "@/components/ui/toast"
import { useAuth } from "@/components/auth-provider"

const empty = (code: string = ""): Omit<Branch, "id" | "createdAt" | "createdBy"> => ({
  name: "", code, type: "outlet", address: "", city: "", country: "", phone: "", email: "", manager: "", status: "active", notes: "",
})

async function generateSingleBranchPdf(branch: Branch, inventoryRows: any[]) {
  const [{ default: jsPDF }, autoTableModule] = await Promise.all([
    import("jspdf"),
    import("jspdf-autotable"),
  ])
  const autoTable = (autoTableModule as any).default || autoTableModule
  const doc = new jsPDF("p", "mm", "a4")
  
  doc.setFontSize(14)
  doc.text(`Inventory Report: ${branch.name}`, 14, 16)
  
  doc.setFontSize(10)
  doc.text(`Branch Code: ${branch.code}`, 14, 22)
  doc.text(`Type: ${branch.type.replace("_", " ")}`, 14, 27)
  doc.text(`Generated: ${new Date().toLocaleString()}`, 14, 32)
  
  const body = inventoryRows.map(inv => [
    inv.productDescription || inv.itemName || inv.inventoryId || "N/A",
    String(inv.quantity),
    inv.unit || "",
    inv.assignedAt ? new Date(inv.assignedAt).toLocaleDateString() : "-"
  ])

  autoTable(doc, {
    startY: 38,
    head: [["Item Description", "Qty", "Unit", "Date"]],
    body: body,
    styles: { fontSize: 8, cellPadding: 2 },
    headStyles: { fillColor: [31, 172, 166] },
  })
  
  doc.save(`${branch.code}-inventory-${new Date().toISOString().slice(0, 10)}.pdf`)
}

// â”€â”€ Branch Form â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
function BranchForm({ initial, onSave, onCancel, isLoading, autoGenerated }: {
  initial: Omit<Branch, "id" | "createdAt" | "createdBy">
  onSave: (b: Omit<Branch, "id" | "createdAt" | "createdBy">) => void
  onCancel: () => void
  isLoading?: boolean
  autoGenerated?: boolean
}) {
  const [form, setForm] = useState(initial)
  const set = (k: keyof typeof form, v: string) => setForm(f => ({ ...f, [k]: v }))

  return (
    <form onSubmit={e => { e.preventDefault(); onSave(form) }}
      className="border rounded-lg p-4 space-y-3 bg-[hsl(var(--muted))]/20">
      <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
        <div className="space-y-1 sm:col-span-2">
          <label className="text-xs font-medium">Branch Name *</label>
          <input required value={form.name} onChange={e => set("name", e.target.value)}
            placeholder="e.g. Main Outlet"
            className="w-full h-8 rounded-md border bg-[hsl(var(--background))] px-3 text-sm focus:outline-none focus:ring-1 focus:ring-[hsl(var(--ring))]" />
        </div>
        <div className="space-y-1">
          <label className="text-xs font-medium">Branch Code *</label>
          <input required value={form.code} onChange={e => set("code", e.target.value)}
            placeholder="e.g. BR001"
            readOnly={autoGenerated}
            className={`w-full h-8 rounded-md border bg-[hsl(var(--background))] px-3 text-sm focus:outline-none focus:ring-1 focus:ring-[hsl(var(--ring))] ${autoGenerated ? "bg-[hsl(var(--muted))]/50 cursor-not-allowed" : ""}`}
          />
          {autoGenerated && <p className="text-[10px] text-[hsl(var(--muted-foreground))]">Auto-generated</p>}
        </div>
        <div className="space-y-1">
          <label className="text-xs font-medium">Type *</label>
          <select required value={form.type} onChange={e => set("type", e.target.value)}
            className="w-full h-8 rounded-md border bg-[hsl(var(--background))] px-3 text-sm focus:outline-none focus:ring-1 focus:ring-[hsl(var(--ring))]">
            <option value="outlet">Outlet</option>
            <option value="store">Store</option>
            <option value="warehouse">Warehouse</option>
            <option value="branch_warehouse">Branch Warehouse</option>
            <option value="main_warehouse">Main Warehouse</option>
            <option value="office">Office</option>
          </select>
        </div>
        <div className="space-y-1">
          <label className="text-xs font-medium">Manager</label>
          <input value={form.manager} onChange={e => set("manager", e.target.value)}
            placeholder="Manager name"
            className="w-full h-8 rounded-md border bg-[hsl(var(--background))] px-3 text-sm focus:outline-none focus:ring-1 focus:ring-[hsl(var(--ring))]" />
        </div>
        <div className="space-y-1">
          <label className="text-xs font-medium">Status *</label>
          <select required value={form.status} onChange={e => set("status", e.target.value)}
            className="w-full h-8 rounded-md border bg-[hsl(var(--background))] px-3 text-sm focus:outline-none focus:ring-1 focus:ring-[hsl(var(--ring))]">
            <option value="active">Active</option>
            <option value="inactive">Inactive</option>
          </select>
        </div>
        <div className="space-y-1">
          <label className="text-xs font-medium">Phone</label>
          <input value={form.phone} onChange={e => set("phone", e.target.value)}
            placeholder="+92 300 0000000"
            className="w-full h-8 rounded-md border bg-[hsl(var(--background))] px-3 text-sm focus:outline-none focus:ring-1 focus:ring-[hsl(var(--ring))]" />
        </div>
        <div className="space-y-1">
          <label className="text-xs font-medium">Email</label>
          <input type="email" value={form.email} onChange={e => set("email", e.target.value)}
            className="w-full h-8 rounded-md border bg-[hsl(var(--background))] px-3 text-sm focus:outline-none focus:ring-1 focus:ring-[hsl(var(--ring))]" />
        </div>
        <div className="space-y-1">
          <label className="text-xs font-medium">Location</label>
          <input value={form.city} onChange={e => set("city", e.target.value)}
            className="w-full h-8 rounded-md border bg-[hsl(var(--background))] px-3 text-sm focus:outline-none focus:ring-1 focus:ring-[hsl(var(--ring))]" />
        </div>
        <div className="space-y-1 sm:col-span-2">
          <label className="text-xs font-medium">Address</label>
          <input value={form.address} onChange={e => set("address", e.target.value)}
            className="w-full h-8 rounded-md border bg-[hsl(var(--background))] px-3 text-sm focus:outline-none focus:ring-1 focus:ring-[hsl(var(--ring))]" />
        </div>
        <div className="space-y-1">
          <label className="text-xs font-medium">Country</label>
          <input value={form.country} onChange={e => set("country", e.target.value)}
            className="w-full h-8 rounded-md border bg-[hsl(var(--background))] px-3 text-sm focus:outline-none focus:ring-1 focus:ring-[hsl(var(--ring))]" />
        </div>
        <div className="space-y-1 sm:col-span-2">
          <label className="text-xs font-medium">Notes</label>
          <textarea value={form.notes} onChange={e => set("notes", e.target.value)} rows={2}
            className="w-full rounded-md border bg-[hsl(var(--background))] px-3 py-2 text-sm focus:outline-none focus:ring-1 focus:ring-[hsl(var(--ring))] resize-none" />
        </div>
      </div>
      <div className="flex gap-2">
        <Button type="submit" size="sm" className="h-8 cursor-pointer" disabled={isLoading}>
          {isLoading ? (
            <>
              <Loader2 className="h-3.5 w-3.5 animate-spin mr-1" />
              Saving...
            </>
          ) : (
            "Save Branch"
          )}
        </Button>
        <Button type="button" variant="outline" size="sm" className="h-8 cursor-pointer" onClick={onCancel} disabled={isLoading}>Cancel</Button>
      </div>
    </form>
  )
}

// â”€â”€ Main Tab â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
export function BranchesTab() {
  const [branches, setBranches] = useState<Branch[]>([])
  const [loading, setLoading] = useState(true)
  const [adding, setAdding] = useState(false)
  const [editId, setEditId] = useState<string | null>(null)
  const [viewBranch, setViewBranch] = useState<Branch | null>(null)
  const [saving, setSaving] = useState(false)
  const [autoCode, setAutoCode] = useState("")
  const [exportPreviewOpen, setExportPreviewOpen] = useState(false)
  const [exportLoading, setExportLoading] = useState(false)
  const [resettingAll, setResettingAll] = useState(false)
  const [exportRows, setExportRows] = useState<Array<{
    branchName: string
    branchCode: string
    branchType: string
    item: string
    qty: number
    unit: string
    transferredAt: string
  }>>([])
  const { confirm } = useDialog()
  const { toast } = useToast()
  const { user } = useAuth()

  useEffect(() => {
    getBranches().then(b => { setBranches(b); setLoading(false) })
    const interval = setInterval(() => getBranches().then(setBranches), 30000)
    return () => clearInterval(interval)
  }, [])

  async function handleAdd(data: Omit<Branch, "id" | "createdAt" | "createdBy">) {
    setSaving(true)
    const b: Branch = {
      ...data,
      id: crypto.randomUUID(),
      createdAt: new Date().toISOString(),
      createdBy: user?.name || "system",
    }
    try {
      const saved = await saveBranch(b)
      setBranches((prev) => [...prev, saved])
      setAdding(false)
      setAutoCode("")
      toast({
        type: "success",
        title: "Branch Created",
        message: `${saved.name} has been added successfully.`,
        duration: 3000,
      })
    } catch (error) {
      toast({
        type: "error",
        title: "Error",
        message: error instanceof Error ? error.message : "Failed to create branch. Please try again.",
        duration: 5000,
      })
    } finally {
      setSaving(false)
    }
  }

  async function handleEdit(id: string, data: Omit<Branch, "id" | "createdAt" | "createdBy">) {
    setSaving(true)
    const existing = branches.find(b => b.id === id)
    const b: Branch = { ...data, id, createdAt: existing?.createdAt || new Date().toISOString(), createdBy: existing?.createdBy || user?.name || "system" }
    try {
      const saved = await saveBranch(b)
      setBranches((prev) => prev.map((x) => (x.id === id ? saved : x)))
      setEditId(null)
      setViewBranch(saved)
      toast({
        type: "success",
        title: "Branch Updated",
        message: `${saved.name} has been updated successfully.`,
        duration: 3000,
      })
    } catch (error) {
      toast({
        type: "error",
        title: "Error",
        message: error instanceof Error ? error.message : "Failed to update branch. Please try again.",
        duration: 5000,
      })
    } finally {
      setSaving(false)
    }
  }

  async function handleResetAllBranches() {
    const ok = await confirm({
      type: "confirm",
      title: "Reset all branch transfers",
      message:
        "Return all transferred inventory to the main warehouse and clear transfer history for every branch? This cannot be undone.",
      confirmLabel: "Reset everything",
    })
    if (!ok) return
    setResettingAll(true)
    try {
      await resetBranchInventory({ all: true })
      if (viewBranch) {
        setViewBranch(null)
      }
      toast({
        type: "success",
        title: "Reset complete",
        message: "All stock is back in the main warehouse and transfer history has been cleared.",
        duration: 4000,
      })
    } catch {
      toast({
        type: "error",
        title: "Reset failed",
        message: "Could not reset branch inventory and transfer history.",
        duration: 4000,
      })
    } finally {
      setResettingAll(false)
    }
  }

  async function handleDelete(id: string) {
    const ok = await confirm({
      type: "confirm",
      title: "Delete Branch",
      message: "This branch will be permanently removed.",
      confirmLabel: "Delete",
    })
    if (!ok) return
    await deleteBranch(id)
    setBranches(prev => prev.filter(b => b.id !== id))
    setViewBranch(null)
  }

  async function buildInventoryExportRows() {
    const targetBranches = branches.filter(b =>
      ["main_warehouse", "branch_warehouse", "warehouse", "store"].includes(b.type)
    )
    const rows = await Promise.all(
      targetBranches.map(async b => {
        const items = await getBranchInventory(b.id)
        return items.map(item => ({
          branchName: b.name,
          branchCode: b.code,
          branchType: b.type,
          item: item.productDescription || item.inventoryId,
          qty: item.quantity,
          unit: item.unit,
          transferredAt: item.assignedAt ? new Date(item.assignedAt).toLocaleDateString() : "-",
        }))
      })
    )
    return rows.flat()
  }

  async function handleOpenExportPreview() {
    setExportLoading(true)
    try {
      const rows = await buildInventoryExportRows()
      setExportRows(rows)
      setExportPreviewOpen(true)
    } finally {
      setExportLoading(false)
    }
  }

  async function handleExportPdf() {
    const rows = exportRows.length ? exportRows : await buildInventoryExportRows()
    const [{ default: jsPDF }, autoTableModule] = await Promise.all([
      import("jspdf"),
      import("jspdf-autotable"),
    ])
    const autoTable = (autoTableModule as any).default || autoTableModule
    const doc = new jsPDF("p", "mm", "a4")
    doc.setFontSize(14)
    doc.text("Warehouse and Store Inventory Report", 14, 16)
    doc.setFontSize(10)
    doc.text(`Generated: ${new Date().toLocaleString()}`, 14, 22)
    autoTable(doc, {
      startY: 26,
      head: [["Branch", "Code", "Type", "Item", "Qty", "Unit", "Transferred/Added Date"]],
      body: rows.map(r => [r.branchName, r.branchCode, r.branchType, r.item, String(r.qty), r.unit, r.transferredAt]),
      styles: { fontSize: 8, cellPadding: 2 },
      headStyles: { fillColor: [31, 172, 166] },
    })
    doc.save(`branch-inventory-report-${new Date().toISOString().slice(0, 10)}.pdf`)
  }

  const editingBranch = branches.find(b => b.id === editId)

  if (viewBranch && !editId) {
    return (
      <BranchDetailView
        branch={viewBranch}
        branches={branches}
        onBack={() => setViewBranch(null)}
        onEdit={() => {
          setEditId(viewBranch.id)
          setViewBranch(null)
        }}
        onDelete={() => handleDelete(viewBranch.id)}
      />
    )
  }

  function formatBranchType(type: Branch["type"]) {
    if (type === "main_warehouse") return "Main warehouse"
    if (type === "branch_warehouse") return "Branch warehouse"
    return type.charAt(0).toUpperCase() + type.slice(1).replace(/_/g, " ")
  }

  return (
    <div className="space-y-4">
      {loading ? (
        <div className="flex flex-col items-center justify-center py-20 gap-3">
          <Loader2 className="h-6 w-6 animate-spin text-[hsl(var(--muted-foreground))]" />
          <p className="text-sm text-[hsl(var(--muted-foreground))]">Loading branches…</p>
        </div>
      ) : (
        <>
          <div className="flex flex-wrap items-start justify-between gap-3 rounded-lg border bg-[hsl(var(--card))] px-4 py-3 shadow-sm">
            <div className="flex items-center gap-3 min-w-0">
              <div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-lg bg-[#1faca6]/15 text-[#1faca6]">
                <Building2 className="h-5 w-5" />
              </div>
              <div>
                <h2 className="text-base font-semibold leading-tight">Branches & warehouses</h2>
                <p className="text-xs text-[hsl(var(--muted-foreground))] mt-0.5">
                  {branches.length} location{branches.length === 1 ? "" : "s"} · click a row to open inventory
                </p>
              </div>
            </div>
            <div className="flex flex-wrap items-center gap-1.5">
              <Button
                size="sm"
                variant="outline"
                className="h-8 text-xs cursor-pointer text-red-600 border-red-200 hover:bg-red-50"
                onClick={handleResetAllBranches}
                disabled={resettingAll}
              >
                {resettingAll ? <Loader2 className="h-3.5 w-3.5 animate-spin mr-1" /> : <Trash2 className="h-3.5 w-3.5 mr-1" />}
                Reset transfers
              </Button>
              <Button
                size="sm"
                variant="outline"
                className="h-8 text-xs cursor-pointer"
                onClick={handleOpenExportPreview}
                disabled={exportLoading}
              >
                {exportLoading ? <Loader2 className="h-3.5 w-3.5 animate-spin mr-1" /> : <FileDown className="h-3.5 w-3.5 mr-1" />}
                Export PDF
              </Button>
              <Button
                size="sm"
                className="h-8 text-xs cursor-pointer bg-[#1faca6] hover:bg-[#17857f] text-white"
                onClick={async () => {
                  const code = await generateBranchCode()
                  setAutoCode(code)
                  setAdding(true)
                  setEditId(null)
                }}
              >
                <Plus className="h-3.5 w-3.5 mr-1" />
                Add branch
              </Button>
            </div>
          </div>

          {branches.length === 0 && !adding && (
            <div className="flex flex-col items-center justify-center py-16 text-center gap-2 rounded-lg border border-dashed">
              <Building2 className="h-10 w-10 text-[hsl(var(--muted-foreground))] opacity-30" />
              <p className="text-sm font-medium">No branches yet</p>
              <p className="text-xs text-[hsl(var(--muted-foreground))]">Add your first branch or warehouse.</p>
            </div>
          )}

          {branches.length > 0 && (
            <div className="rounded-lg border overflow-hidden bg-[hsl(var(--card))] shadow-sm">
              <table className="w-full text-sm">
                <thead>
                  <tr className="border-b bg-[hsl(var(--muted))]/30">
                    {["Name", "Code", "Type", "Manager", "Status", ""].map((h) => (
                      <th
                        key={h || "actions"}
                        className="h-9 px-4 text-left text-[10px] font-semibold uppercase tracking-wide text-[hsl(var(--muted-foreground))]"
                      >
                        {h}
                      </th>
                    ))}
                  </tr>
                </thead>
                <tbody className="divide-y divide-[hsl(var(--border))]">
                  {branches.map((b) => (
                    <tr
                      key={b.id}
                      onClick={() => {
                        setViewBranch(b)
                        setEditId(null)
                      }}
                      className="group hover:bg-[#1faca6]/5 transition-colors cursor-pointer"
                    >
                      <td className="px-4 py-2.5">
                        <div className="flex items-center gap-2 min-w-0">
                          <span className="font-medium text-[hsl(var(--foreground))] truncate">{b.name}</span>
                          <ChevronRight className="h-3.5 w-3.5 shrink-0 text-[hsl(var(--muted-foreground))] opacity-0 group-hover:opacity-100" />
                        </div>
                      </td>
                      <td className="px-4 py-2.5 font-mono text-xs text-[hsl(var(--muted-foreground))]">{b.code}</td>
                      <td className="px-4 py-2.5">
                        <Badge variant="info" className="text-[10px] px-1.5 py-0 font-normal">
                          {formatBranchType(b.type)}
                        </Badge>
                      </td>
                      <td className="px-4 py-2.5 text-xs text-[hsl(var(--muted-foreground))]">{b.manager || "—"}</td>
                      <td className="px-4 py-2.5">
                        <Badge variant={b.status === "active" ? "success" : "secondary"} className="text-[10px] px-1.5 py-0 capitalize">
                          {b.status}
                        </Badge>
                      </td>
                      <td className="px-4 py-2.5">
                        <div className="flex items-center justify-end gap-0.5" onClick={(e) => e.stopPropagation()}>
                          <Button
                            variant="ghost"
                            size="icon"
                            className="h-7 w-7 text-[#1faca6] hover:bg-[#1faca6]/10"
                            title="Export inventory PDF"
                            onClick={async () => {
                              const inv = await getBranchInventory(b.id)
                              generateSingleBranchPdf(b, inv)
                            }}
                          >
                            <FileDown className="h-3.5 w-3.5" />
                          </Button>
                          <Button
                            variant="ghost"
                            size="icon"
                            className="h-7 w-7 text-[hsl(var(--muted-foreground))] hover:text-red-600 hover:bg-red-50"
                            title="Delete branch"
                            onClick={() => handleDelete(b.id)}
                          >
                            <Trash2 className="h-3.5 w-3.5" />
                          </Button>
                        </div>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}
        </>
      )}

      {/* Add modal */}
      {adding && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 backdrop-blur-sm p-4" onClick={() => setAdding(false)}>
          <div className="w-full max-w-lg rounded-xl border bg-[hsl(var(--card))] shadow-xl overflow-hidden" onClick={e => e.stopPropagation()}>
            <div className="flex items-center justify-between px-5 py-4 border-b">
              <p className="text-sm font-semibold">Add Branch</p>
              <Button variant="ghost" size="icon" className="h-7 w-7" onClick={() => setAdding(false)}>
                <X className="h-4 w-4" />
              </Button>
            </div>
            <div className="p-5">
              <BranchForm initial={empty(autoCode)} onSave={handleAdd} onCancel={() => setAdding(false)} isLoading={saving} autoGenerated={!!autoCode} />
            </div>
          </div>
        </div>
      )}

      {/* Edit modal */}
      {editId && editingBranch && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 backdrop-blur-sm p-4" onClick={() => setEditId(null)}>
          <div className="w-full max-w-lg rounded-xl border bg-[hsl(var(--card))] shadow-xl p-6 space-y-4" onClick={e => e.stopPropagation()}>
            <div className="flex items-center justify-between">
              <p className="text-sm font-semibold">Edit Branch</p>
              <Button variant="ghost" size="icon" className="h-7 w-7" onClick={() => setEditId(null)}>
                <X className="h-4 w-4" />
              </Button>
            </div>
            <BranchForm
              initial={{ name: editingBranch.name, code: editingBranch.code, type: editingBranch.type, address: editingBranch.address, city: editingBranch.city, country: editingBranch.country, phone: editingBranch.phone, email: editingBranch.email, manager: editingBranch.manager, status: editingBranch.status, notes: editingBranch.notes }}
              onSave={data => handleEdit(editId, data)}
              onCancel={() => setEditId(null)}
              isLoading={saving}
              autoGenerated={false}
            />
          </div>
        </div>
      )}

      {exportPreviewOpen && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 backdrop-blur-sm p-4" onClick={() => setExportPreviewOpen(false)}>
          <div className="w-full max-w-5xl rounded-xl border bg-[hsl(var(--card))] shadow-xl overflow-hidden" onClick={e => e.stopPropagation()}>
            <div className="flex items-center justify-between px-5 py-4 border-b">
              <p className="text-sm font-semibold">Inventory Export Preview</p>
              <Button variant="ghost" size="icon" className="h-7 w-7" onClick={() => setExportPreviewOpen(false)}>
                <X className="h-4 w-4" />
              </Button>
            </div>
            <div className="p-5">
              {exportRows.length === 0 ? (
                <p className="text-xs text-[hsl(var(--muted-foreground))]">No inventory rows found for warehouses/stores.</p>
              ) : (
                <div className="max-h-[55vh] overflow-auto rounded-md border">
                  <table className="w-full text-xs">
                    <thead className="bg-[hsl(var(--muted))]/40 sticky top-0">
                      <tr>
                        {["Branch", "Code", "Type", "Item", "Qty", "Unit", "Transferred/Added Date"].map(h => (
                          <th key={h} className="px-3 py-2 text-left font-semibold">{h}</th>
                        ))}
                      </tr>
                    </thead>
                    <tbody>
                      {exportRows.map((row, index) => (
                        <tr key={`${row.branchCode}-${row.item}-${index}`} className="border-t">
                          <td className="px-3 py-2">{row.branchName}</td>
                          <td className="px-3 py-2">{row.branchCode}</td>
                          <td className="px-3 py-2">{row.branchType}</td>
                          <td className="px-3 py-2">{row.item}</td>
                          <td className="px-3 py-2">{row.qty}</td>
                          <td className="px-3 py-2">{row.unit}</td>
                          <td className="px-3 py-2">{row.transferredAt}</td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              )}
            </div>
            <div className="px-5 py-3 border-t flex justify-end gap-2 bg-[hsl(var(--muted))]/20">
              <Button size="sm" variant="outline" className="h-8 text-xs cursor-pointer" onClick={() => setExportPreviewOpen(false)}>
                Close
              </Button>
              <Button size="sm" className="h-8 text-xs cursor-pointer bg-[#1faca6] hover:bg-[#17857f] text-white" onClick={handleExportPdf}>
                <FileDown className="h-3.5 w-3.5" />
                Export PDF
              </Button>
            </div>
          </div>
        </div>
      )}

    </div>
  )
}
