ALTER TABLE "erp_purchase_ledger" ADD COLUMN IF NOT EXISTS "amount_paid" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "erp_purchase_ledger" ADD COLUMN IF NOT EXISTS "amount_due" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "erp_purchase_ledger" ADD COLUMN IF NOT EXISTS "items" JSONB NOT NULL DEFAULT '[]';
ALTER TABLE "erp_purchase_ledger" ADD COLUMN IF NOT EXISTS "payments" JSONB NOT NULL DEFAULT '[]';
